/**
 * Localized developer documentation for Custom Lead API (Integrations → Lead API).
 * Rendered language follows company owner preference from lead-api-config.
 */

export const leadApiDocumentationTranslations = {
  en: {
    leadApiDocPageTitle: 'Custom Lead API — Developer documentation',
    leadApiDocLanguageNote:
      'This guide follows your CRM language. Change it under Profile → Language.',
    leadApiDocBackToSetup: 'Back to setup',
    leadApiDocToc: 'On this page',
    leadApiDocSectionOverview: 'Overview',
    leadApiDocSectionHowItWorks: 'How it works',
    leadApiDocSectionQuickStart: 'Quick start',
    leadApiDocSectionEndpoint: 'Endpoint',
    leadApiDocSectionAuth: 'Authentication',
    leadApiDocSectionRequest: 'Request body',
    leadApiDocSectionResponse: 'Responses',
    leadApiDocSectionErrors: 'Error codes',
    leadApiDocSectionIdempotency: 'Idempotency',
    leadApiDocSectionSecurity: 'Security',
    leadApiDocSectionOptionalIds: 'Campaign, status & channel IDs',
    leadApiDocSectionSamples: 'Code examples',
    leadApiDocSectionTroubleshooting: 'Troubleshooting',
    leadApiDocOverview:
      'The Custom Lead API lets your website, mobile app, or backend send leads into your CRM in real time. Each company has its own API keys and endpoint. Leads appear in the Leads list with source “Custom API”.',
    leadApiDocHowItWorksIntro:
      'Your server sends an HTTPS POST with JSON. The CRM validates your API key, creates a lead (or returns an existing one if you reuse external_id), and may notify the company owner.',
    leadApiDocHowItWorksStep1: 'Generate an API key under Integrations → Lead API (company owner only).',
    leadApiDocHowItWorksStep2: 'Store the key on your server — never expose it in public front-end code.',
    leadApiDocHowItWorksStep3: 'POST JSON to the endpoint URL when a form is submitted or an event occurs.',
    leadApiDocHowItWorksStep4: 'Handle 201 (created) or 200 (duplicate) and store client_id if you need it later.',
    leadApiDocQuickStart1: 'Copy the endpoint URL from the setup tab.',
    leadApiDocQuickStart2: 'Create an API key and copy the secret immediately (shown once).',
    leadApiDocQuickStart3: 'Send a test POST with name and external_id from your backend or cURL.',
    leadApiDocQuickStart4: 'Confirm the lead appears in CRM → Leads.',
    leadApiDocEndpointMethod: 'Method: POST',
    leadApiDocEndpointContentType: 'Content-Type: application/json',
    leadApiDocEndpointYourUrl: 'Your endpoint URL',
    leadApiDocAuthIntro:
      'Send your company API key using exactly one of the following headers. Keys start with crm_lk_.',
    leadApiDocAuthBearer: 'Authorization: Bearer crm_lk_…',
    leadApiDocAuthHeader: 'X-Lead-Api-Key: crm_lk_…',
    leadApiDocAuthDoNot:
      'Do not use the global CRM X-API-Key (mobile/web app key) on this endpoint — it will not work.',
    leadApiDocFieldName: 'name',
    leadApiDocFieldPhone: 'phone',
    leadApiDocFieldExternalId: 'external_id',
    leadApiDocFieldEmail: 'email',
    leadApiDocFieldNotes: 'notes',
    leadApiDocFieldCampaignId: 'campaign_id',
    leadApiDocFieldCommunicationWayId: 'communication_way_id',
    leadApiDocFieldStatusId: 'status_id',
    leadApiDocFieldPriority: 'priority',
    leadApiDocFieldType: 'type',
    leadApiDocFieldCustomFields: 'custom_fields',
    leadApiDocRequiredYes: 'Required',
    leadApiDocRequiredRecommended: 'Recommended',
    leadApiDocRequiredNo: 'Optional',
    leadApiDocDescName: 'Lead full name',
    leadApiDocDescPhone: 'Primary phone; also stored as a phone record on the lead',
    leadApiDocDescExternalId:
      'Your unique submission id (UUID, order id, etc.) — used for idempotency',
    leadApiDocDescEmail: 'Stored in lead notes (not a separate email field)',
    leadApiDocDescNotes: 'Free-text notes',
    leadApiDocDescCampaignId: 'Must belong to your company (Marketing → Campaigns)',
    leadApiDocDescCommunicationWayId: 'Channel id from Settings → Channels',
    leadApiDocDescStatusId: 'Lead status id from Settings; defaults to company default status',
    leadApiDocDescPriority: 'low | medium (default) | high',
    leadApiDocDescType: 'fresh (default) | hot | cold',
    leadApiDocDescCustomFields: 'JSON object; serialized into notes',
    leadApiDocExampleRequest: 'Example request',
    leadApiDocEnvelope:
      'All responses use the CRM JSON envelope: { "success": true|false, "data"?: …, "error"?: { "code", "message", "details"? } }',
    leadApiDocHttp201: '201 — Lead created',
    leadApiDocHttp200: '200 — Duplicate external_id (same client_id, duplicate: true)',
    leadApiDocHttp400: '400 — Validation error (code: validation_error)',
    leadApiDocHttp401: '401 — Missing or invalid API key',
    leadApiDocHttp403: '403 — Integration disabled or plan lead quota exceeded',
    leadApiDocHttp429: '429 — Rate limit exceeded (120 requests/minute per IP)',
    leadApiDocHttp500: '500 — Unexpected error (code: lead_create_failed)',
    leadApiDocSuccessExample: 'Success (201)',
    leadApiDocDuplicateExample: 'Idempotent replay (200)',
    leadApiDocValidationExample: 'Validation error (400)',
    leadApiDocIdempotency:
      'If you send the same external_id twice for your company, the second call returns HTTP 200 with the existing client_id and duplicate: true. Always send a stable external_id per form submission.',
    leadApiDocSecurity1: 'Use HTTPS only in production.',
    leadApiDocSecurity2:
      'For public websites, POST from your backend (proxy), not from the browser, so the API key stays secret.',
    leadApiDocSecurity3: 'Rotate or revoke keys from Integrations if a key is exposed.',
    leadApiDocSecurity4: 'Use environment variables or a secrets manager for keys.',
    leadApiDocOptionalIdsIntro:
      'Optional ids must exist for your company. Find them in the CRM UI or via authenticated CRM APIs (not with the Lead API key).',
    leadApiDocOptionalIdsCampaign: 'campaign_id — Marketing → Campaigns (numeric id)',
    leadApiDocOptionalIdsStatus: 'status_id — Settings → Lead statuses',
    leadApiDocOptionalIdsChannel: 'communication_way_id — Settings → Channels',
    leadApiDocCopy: 'Copy',
    leadApiDocCopied: 'Copied',
    leadApiDocSampleCurl: 'cURL',
    leadApiDocSampleJs: 'JavaScript (fetch)',
    leadApiDocSamplePhp: 'PHP',
    leadApiDocSamplePython: 'Python (requests)',
    leadApiDocErrMissingApiKey: 'missing_api_key — No Bearer / X-Lead-Api-Key header',
    leadApiDocErrInvalidApiKey: 'invalid_api_key — Unknown or revoked key',
    leadApiDocErrInvalidJson: 'invalid_json — Body is not valid JSON',
    leadApiDocErrIntegrationDisabled: 'integration_disabled — Lead API disabled by plan or admin policy',
    leadApiDocErrQuota: 'plan_quota_max_clients_exceeded — Company reached lead limit on plan',
    leadApiDocErrValidation: 'validation_error — Invalid field values (see details)',
    leadApiDocTs401: '401 Unauthorized — Check key spelling and that the key is active',
    leadApiDocTs403: '403 Forbidden — Enable integration on plan or contact support; check lead quota',
    leadApiDocTs400: '400 Bad Request — name is required; campaign/status/channel must belong to your company',
    leadApiDocTsNoLead: 'Lead not in CRM — Confirm 201/200 response; check correct company key',
    leadApiDocTsRateLimit: '429 — Slow down; max ~120 requests per minute per IP',
    leadApiDocViewDocumentation: 'Developer documentation',
    leadApiDocTabSetup: 'Setup',
    leadApiDocTabDocs: 'Documentation',
  },
  ar: {
    leadApiDocPageTitle: 'واجهة الليدز المخصصة — دليل المطورين',
    leadApiDocLanguageNote:
      'يتبع هذا الدليل لغة الـ CRM الحالية. لتغييرها: الملف الشخصي → اللغة.',
    leadApiDocBackToSetup: 'العودة للإعداد',
    leadApiDocToc: 'في هذه الصفحة',
    leadApiDocSectionOverview: 'نظرة عامة',
    leadApiDocSectionHowItWorks: 'آلية العمل',
    leadApiDocSectionQuickStart: 'بدء سريع',
    leadApiDocSectionEndpoint: 'نقطة النهاية',
    leadApiDocSectionAuth: 'المصادقة',
    leadApiDocSectionRequest: 'جسم الطلب',
    leadApiDocSectionResponse: 'الاستجابات',
    leadApiDocSectionErrors: 'رموز الأخطاء',
    leadApiDocSectionIdempotency: 'منع التكرار',
    leadApiDocSectionSecurity: 'الأمان',
    leadApiDocSectionOptionalIds: 'معرّفات الحملة والحالة والقناة',
    leadApiDocSectionSamples: 'أمثلة برمجية',
    leadApiDocSectionTroubleshooting: 'استكشاف الأخطاء',
    leadApiDocOverview:
      'تتيح واجهة الليدز المخصصة لموقعك أو تطبيقك أو السيرفر إرسال الليدز إلى الـ CRM فوراً. لكل شركة مفاتيح API خاصة ونقطة نهاية واحدة. تظهر الليدز في قائمة الليدز بمصدر «واجهة API».',
    leadApiDocHowItWorksIntro:
      'يرسل السيرفر طلب HTTPS POST بصيغة JSON. يتحقق الـ CRM من مفتاح API، ينشئ ليداً (أو يعيد الموجود عند إعادة استخدام external_id)، وقد يُشعر مالك الشركة.',
    leadApiDocHowItWorksStep1: 'أنشئ مفتاح API من التكاملات → واجهة الليدز (مالك الشركة فقط).',
    leadApiDocHowItWorksStep2: 'احفظ المفتاح على السيرفر — لا تعرضه في كود الواجهة العامة.',
    leadApiDocHowItWorksStep3: 'أرسل JSON إلى رابط الـ API عند إرسال نموذج أو حدوث حدث.',
    leadApiDocHowItWorksStep4: 'عالج 201 (إنشاء) أو 200 (مكرر) واحفظ client_id إن احتجته لاحقاً.',
    leadApiDocQuickStart1: 'انسخ رابط الـ API من تبويب الإعداد.',
    leadApiDocQuickStart2: 'أنشئ مفتاح API وانسخ السر فوراً (يُعرض مرة واحدة).',
    leadApiDocQuickStart3: 'أرسل POST تجريبي يتضمن name و external_id من السيرفر أو cURL.',
    leadApiDocQuickStart4: 'تأكد من ظهور الليد في CRM → الليدز.',
    leadApiDocEndpointMethod: 'الطريقة: POST',
    leadApiDocEndpointContentType: 'Content-Type: application/json',
    leadApiDocEndpointYourUrl: 'رابط الـ API الخاص بك',
    leadApiDocAuthIntro:
      'أرسل مفتاح API الخاص بشركتك بأحد الترويستين التاليتين. المفاتيح تبدأ بـ crm_lk_.',
    leadApiDocAuthBearer: 'Authorization: Bearer crm_lk_…',
    leadApiDocAuthHeader: 'X-Lead-Api-Key: crm_lk_…',
    leadApiDocAuthDoNot:
      'لا تستخدم X-API-Key العام للـ CRM (مفتاح التطبيق) على هذه النقطة — لن يعمل.',
    leadApiDocFieldName: 'name',
    leadApiDocFieldPhone: 'phone',
    leadApiDocFieldExternalId: 'external_id',
    leadApiDocFieldEmail: 'email',
    leadApiDocFieldNotes: 'notes',
    leadApiDocFieldCampaignId: 'campaign_id',
    leadApiDocFieldCommunicationWayId: 'communication_way_id',
    leadApiDocFieldStatusId: 'status_id',
    leadApiDocFieldPriority: 'priority',
    leadApiDocFieldType: 'type',
    leadApiDocFieldCustomFields: 'custom_fields',
    leadApiDocRequiredYes: 'مطلوب',
    leadApiDocRequiredRecommended: 'موصى به',
    leadApiDocRequiredNo: 'اختياري',
    leadApiDocDescName: 'الاسم الكامل لليد',
    leadApiDocDescPhone: 'الهاتف الأساسي؛ يُخزَّن أيضاً كسجل هاتف على الليد',
    leadApiDocDescExternalId:
      'معرّف الإرسال الفريد لديك (UUID، رقم طلب، إلخ) — لمنع التكرار',
    leadApiDocDescEmail: 'يُخزَّن في ملاحظات الليد (ليس حقل بريد منفصل)',
    leadApiDocDescNotes: 'ملاحظات نصية',
    leadApiDocDescCampaignId: 'يجب أن تنتمي لشركتك (التسويق → الحملات)',
    leadApiDocDescCommunicationWayId: 'معرّف القناة من الإعدادات → القنوات',
    leadApiDocDescStatusId: 'معرّف حالة الليد من الإعدادات؛ الافتراضي حالة الشركة الافتراضية',
    leadApiDocDescPriority: 'low | medium (افتراضي) | high',
    leadApiDocDescType: 'fresh (افتراضي) | hot | cold',
    leadApiDocDescCustomFields: 'كائن JSON؛ يُحفظ ضمن الملاحظات',
    leadApiDocExampleRequest: 'مثال طلب',
    leadApiDocEnvelope:
      'كل الاستجابات تستخدم غلاف JSON: { "success": true|false, "data"?: …, "error"?: { "code", "message", "details"? } }',
    leadApiDocHttp201: '201 — تم إنشاء الليد',
    leadApiDocHttp200: '200 — external_id مكرر (نفس client_id، duplicate: true)',
    leadApiDocHttp400: '400 — خطأ تحقق (code: validation_error)',
    leadApiDocHttp401: '401 — مفتاح API مفقود أو غير صالح',
    leadApiDocHttp403: '403 — التكامل معطّل أو تجاوز حد الليدز في الخطة',
    leadApiDocHttp429: '429 — تجاوز حد المعدل (120 طلب/دقيقة لكل IP)',
    leadApiDocHttp500: '500 — خطأ غير متوقع (code: lead_create_failed)',
    leadApiDocSuccessExample: 'نجاح (201)',
    leadApiDocDuplicateExample: 'إعادة بنفس external_id (200)',
    leadApiDocValidationExample: 'خطأ تحقق (400)',
    leadApiDocIdempotency:
      'عند إرسال نفس external_id مرتين لشركتك، يعيد الطلب الثاني HTTP 200 مع client_id الحالي و duplicate: true. أرسل دائماً external_id ثابتاً لكل إرسال نموذج.',
    leadApiDocSecurity1: 'استخدم HTTPS فقط في الإنتاج.',
    leadApiDocSecurity2:
      'للمواقع العامة، أرسل من السيرفر (وسيط) وليس من المتصفح ليبقى المفتاح سرياً.',
    leadApiDocSecurity3: 'جدّد أو ألغِ المفاتيح من التكاملات عند تسريب مفتاح.',
    leadApiDocSecurity4: 'استخدم متغيرات البيئة أو مدير أسرار للمفاتيح.',
    leadApiDocOptionalIdsIntro:
      'المعرّفات الاختيارية يجب أن تكون لشركتك. اعثر عليها من واجهة الـ CRM أو عبر APIs المصادق عليها (وليس بمفتاح Lead API).',
    leadApiDocOptionalIdsCampaign: 'campaign_id — التسويق → الحملات (رقم المعرّف)',
    leadApiDocOptionalIdsStatus: 'status_id — الإعدادات → حالات الليد',
    leadApiDocOptionalIdsChannel: 'communication_way_id — الإعدادات → القنوات',
    leadApiDocCopy: 'نسخ',
    leadApiDocCopied: 'تم النسخ',
    leadApiDocSampleCurl: 'cURL',
    leadApiDocSampleJs: 'JavaScript (fetch)',
    leadApiDocSamplePhp: 'PHP',
    leadApiDocSamplePython: 'Python (requests)',
    leadApiDocErrMissingApiKey: 'missing_api_key — لا ترويسة Bearer / X-Lead-Api-Key',
    leadApiDocErrInvalidApiKey: 'invalid_api_key — مفتاح غير معروف أو ملغى',
    leadApiDocErrInvalidJson: 'invalid_json — الجسم ليس JSON صالحاً',
    leadApiDocErrIntegrationDisabled: 'integration_disabled — الواجهة معطّلة بالخطة أو سياسة المسؤول',
    leadApiDocErrQuota: 'plan_quota_max_clients_exceeded — الشركة وصلت حد الليدز في الخطة',
    leadApiDocErrValidation: 'validation_error — قيم حقول غير صالحة (راجع details)',
    leadApiDocTs401: '401 — تحقق من المفتاح وأنه نشط',
    leadApiDocTs403: '403 — فعّل التكامل في الخطة أو تواصل مع الدعم؛ تحقق من حد الليدز',
    leadApiDocTs400: '400 — name مطلوب؛ campaign/status/channel يجب أن تنتمي لشركتك',
    leadApiDocTsNoLead: 'الليد غير ظاهر — تأكد من استجابة 201/200 ومفتاح الشركة الصحيح',
    leadApiDocTsRateLimit: '429 — قلّل المعدل؛ حوالي 120 طلب/دقيقة لكل IP',
    leadApiDocViewDocumentation: 'دليل المطورين',
    leadApiDocTabSetup: 'الإعداد',
    leadApiDocTabDocs: 'التوثيق',
  },
} as const;

export type LeadApiDocKey = keyof typeof leadApiDocumentationTranslations.en;

export function leadApiDocT(lang: 'ar' | 'en', key: LeadApiDocKey): string {
  const pack = leadApiDocumentationTranslations[lang] ?? leadApiDocumentationTranslations.en;
  return pack[key] ?? leadApiDocumentationTranslations.en[key] ?? key;
}
