

import React from 'react';
import { Page, Lead, User, Deal, Todo, Campaign, TimelineEntry, Activity, Developer, Project, Unit, Owner, Channel, Stage, Status, Service, ServicePackage, ServiceProvider, Product, ProductCategory, Supplier } from './types';
import { ChartIcon, CheckSquareIcon, ChevronsUpDownIcon, FileTextIcon, HandshakeIcon, MegaphoneIcon, SettingsIcon, ShoppingBagIcon, StarIcon, TargetIcon, UsersIcon } from './components/index';

export const SIDEBAR_ITEMS: { 
  name: Page; 
  icon: React.FC<React.SVGProps<SVGSVGElement>>; 
  subItems?: Page[] 
}[] = [
  { name: 'Dashboard', icon: ChartIcon },
  { name: 'Leads', icon: TargetIcon, subItems: ['All Leads', 'Fresh Leads', 'Cold Leads', 'My Leads', 'Rotated Leads'] },
  { name: 'Activities', icon: StarIcon },
  { name: 'Inventory', icon: ShoppingBagIcon, subItems: ['Properties', 'Owners'] },
  { name: 'Deals', icon: HandshakeIcon },
  { name: 'Employees', icon: UsersIcon },
  { name: 'Marketing', icon: MegaphoneIcon, subItems: ['Campaigns'] },
  { name: 'Todos', icon: CheckSquareIcon },
  { name: 'Reports', icon: FileTextIcon, subItems: ['Teams Report', 'Employees Report', 'Marketing Report'] },
  { name: 'Integrations', icon: ChevronsUpDownIcon, subItems: ['Meta', 'TikTok', 'WhatsApp'] },
];

export const SETTINGS_ITEM = { name: 'Settings', icon: SettingsIcon };


export const translations = {
    en: {
        hello: "Hello LOOP CRM! 👋",
        welcomeBack: "Welcome Back!",
        signInToContinue: "Sign in to continue managing your customer relationships efficiently.",
        crmWelcome: "The future of customer relationship management.",
        crmDescription: "Automate repetitive tasks, enhance productivity, and improve your workflows with our intuitive CRM.",
        username: "Username",
        usernameOrEmail: "Username or Email",
        password: "Password",
        signIn: "Sign In",
        pleaseEnterCredentials: "Please enter username and password",
        invalidCredentials: "Invalid username or password",
        loginErrorNoActiveAccount: "No active account found with the given credentials",
        loginErrorUnableToLogin: "Unable to log in with provided credentials",
        loginErrorAccountInactive: "Account is inactive",
        loginErrorInvalidCredentials: "Invalid username or password",
        search: "Search",
        searchEllipsis: "Search...",
        all: "All",
        user: "User",
        // Sidebar
        dashboard: "Dashboard",
        leads: "Leads",
        allLeads: "All Leads",
        freshLeads: "Fresh Leads",
        coldLeads: "Cold Leads",
        myLeads: "My Leads",
        rotatedLeads: "Rotated Leads",
        activities: "Activities",
        inventory: "Inventory",
        properties: "Properties",
        owners: "Owners",
        deals: "Deals",
        users: "Users", // Keep for backward compatibility
        employees: "Employees",
        marketing: "Marketing",
        campaigns: "Campaigns",
        // FIX: Added missing translation key.
        campaign: "Campaign",
        todos: "Todos",
        reports: "Reports",
        teamsReport: "Teams Report",
        employeesReport: "Employees Report",
        marketingReport: "Marketing Report",
        integrations: "Integrations",
        meta: "Meta",
        facebook: "Facebook", // Keep for backward compatibility with data
        tikTok: "TikTok",
        whatsApp: "WhatsApp",
        // FIX: Added missing translation key.
        website: "Website",
        settings: "Settings",
        channels: "Channels",
        stages: "Stages",
        statuses: "Statuses",
        logout: "Logout",
        logoutConfirmTitle: "Confirm Logout",
        logoutConfirmMessage: "Are you sure you want to log out?",
        // Dashboard
        todayNewLeads: "Today New Leads",
        todayTouchedLeads: "Today Touched Leads",
        todayUntouchedLeads: "Today Untouched Leads",
        delayedLeads: "Delayed Leads",
        weekLeadsReport: "Week Leads Report",
        last7DaysPerformance: "Last 7 days performance",
        stagesReport: "Stages Report",
        distributionByStage: "Distribution by stage",
        topUsers: "Top Users",
        mostActivePerformers: "Most active performers",
        latestFeedbacks: "Latest Feedbacks",
        recentActivityUpdates: "Recent activity updates",
        noDataAvailable: "No data available",
        noStageDataAvailable: "No stage data available",
        noUserActivityData: "No user activity data",
        noRecentFeedbackAvailable: "No recent feedback available",
        noNotes: "No notes",
        totalLeads: "Total Leads",
        totalDeals: "Total Deals",
        activeTodos: "Active Todos",
        completedDeals: "Completed Deals",
        // Leads
        filter: "Filter",
        addLead: "Add Lead",
        assignLead: "Assign Lead",
        confirmAssignLeads: "Confirm Assignment",
        confirmAssignLeadsMessage: "Are you sure you want to assign",
        confirmAssignLeadsMessage2: "lead(s) to",
        confirmAssign: "Confirm",
        assigning: "Assigning...",
        assignLeadsError: "Failed to assign leads. Please try again.",
        assignToMe: "Assign to Me",
        confirmAssignToMe: "Confirm Assignment",
        confirmAssignToMeMessage: "Are you sure you want to assign this lead to yourself?",
        assignLeadError: "Failed to assign lead. Please try again.",
        noUserSelected: "No user selected",
        name: "Name",
        phone: "Phone",
        actions: "Actions",
        lastFeedback: "Last Feedback",
        notes: "Notes",
        lastStage: "Last Stage",
        reminder: "Reminder",
        view: "View",
        add_action: "Add Action",
        // View Lead
        unassign: "Unassign",
        addDeal: "Add Deal",
        editClient: "Edit Client",
        details: "Details",
        communicationWay: "Communication Way",
        authority: "Authority",
        priority: "Priority",
        dates: "Dates",
        createdAt: "Created At",
        timeline: "Timeline",
        // Activities
        allUsers: "All users",
        today: "Today",
        yesterday: "Yesterday",
        last7Days: "Last 7 Days",
        thisMonth: "This Month",
        allLeadsType: "All Leads Type",
        freshLead: "Fresh Lead",
        coldLead: "Cold Lead",
        call: "Call",
        meeting: "Meeting",
        whatsapp: "Whatsapp",
        note: "Note",
        lead: "Lead",
        type: "Type",
        date: "Date",
        noActivitiesFound: "No activities found for the selected filters.",
        // Properties
        createNew: "Create New",
        addDeveloper: "Add Developer",
        addProject: "Add Project",
        addUnit: "Add Unit",
        // Services
        services: "Services",
        servicePackages: "Service Packages",
        serviceProviders: "Service Providers",
        addService: "Add Service",
        editService: "Edit Service",
        deleteService: "Delete Service",
        confirmDeleteService: "Are you sure you want to delete",
        addServicePackage: "Add Service Package",
        editServicePackage: "Edit Service Package",
        deleteServicePackage: "Delete Service Package",
        confirmDeleteServicePackage: "Are you sure you want to delete",
        addServiceProvider: "Add Service Provider",
        editServiceProvider: "Edit Service Provider",
        deleteServiceProvider: "Delete Service Provider",
        confirmDeleteServiceProvider: "Are you sure you want to delete",
        enterServiceName: "Enter service name",
        enterServiceDescription: "Enter service description",
        enterPackageName: "Enter package name",
        enterPackageDescription: "Enter package description",
        enterProviderName: "Enter provider name",
        enterPhoneNumber: "Enter phone number",
        enterSpecialization: "Enter specialization",
        enterContactPerson: "Enter contact person",
        enterRating: "Enter rating (0-5)",
        selectProvider: "Select Provider (Optional)",
        noServicesAvailable: "No services available",
        provider: "Provider",
        duration: "Duration (hours)",
        rating: "Rating",
        failedToCreateService: "Failed to create service. Please try again.",
        failedToUpdateService: "Failed to update service. Please try again.",
        failedToCreateServicePackage: "Failed to create service package. Please try again.",
        failedToUpdateServicePackage: "Failed to update service package. Please try again.",
        failedToCreateServiceProvider: "Failed to create service provider. Please try again.",
        failedToUpdateServiceProvider: "Failed to update service provider. Please try again.",
        // Products
        products: "Products",
        productCategories: "Product Categories",
        suppliers: "Suppliers",
        addProduct: "Add Product",
        editProduct: "Edit Product",
        deleteProduct: "Delete Product",
        confirmDeleteProduct: "Are you sure you want to delete",
        addProductCategory: "Add Product Category",
        editProductCategory: "Edit Product Category",
        deleteProductCategory: "Delete Product Category",
        confirmDeleteProductCategory: "Are you sure you want to delete",
        addSupplier: "Add Supplier",
        editSupplier: "Edit Supplier",
        deleteSupplier: "Delete Supplier",
        confirmDeleteSupplier: "Are you sure you want to delete",
        enterProductName: "Enter product name",
        enterProductDescription: "Enter product description",
        enterCost: "Enter cost",
        enterStock: "Enter stock",
        selectCategory: "Select Category",
        selectSupplier: "Select Supplier (Optional)",
        enterSKU: "Enter SKU",
        enterCategoryName: "Enter category name",
        enterCategoryDescription: "Enter category description",
        selectParentCategory: "Select Parent Category (Optional)",
        enterSupplierName: "Enter supplier name",
        enterAddress: "Enter address",
        fillRequiredFields: "Please fill in required fields",
        failedToCreateProduct: "Failed to create product. Please try again.",
        failedToUpdateProduct: "Failed to update product. Please try again.",
        failedToCreateProductCategory: "Failed to create product category. Please try again.",
        failedToUpdateProductCategory: "Failed to update product category. Please try again.",
        failedToCreateSupplier: "Failed to create supplier. Please try again.",
        failedToUpdateSupplier: "Failed to update supplier. Please try again.",
        cost: "Cost",
        stock: "Stock",
        sku: "SKU",
        contactPerson: "Contact Person",
        specialization: "Specialization",
        realEstateOnly: "This page is only available for Real Estate companies.",
        servicesOnly: "This page is only available for Services companies.",
        productsOnly: "This page is only available for Products companies.",
        active: "Active",
        inactive: "Inactive",
        units: "Units",
        projects: "Projects",
        developers: "Developers",
        searchUnits: "Search Units",
        searchProjects: "Search Projects",
        searchDevelopers: "Search Developers",
        logo: "Logo",
        developer: "Developer",
        city: "City",
        paymentMethod: "Payment Method",
        update: "Update",
        delete: "Delete",
        bedrooms: "Bedrooms",
        // FIX: Added missing translation key.
        bathrooms: "Bathrooms",
        price: "Price",
        // Owners
        addOwner: "Add Owner",
        district: "District",
        // FIX: Added missing translation key.
        zone: "Zone",
        noOwnersFound: "No owners found.",
        // Deals
        searchDeals: "Search Deals",
        createDeal: "Create Deal",
        dealId: "ID",
        value: "Value",
        noDealsFound: "No deals found.",
        // Create Deal
        createNewDeal: "Create New Deal",
        dealInformation: "Deal Information",
        project: "Project",
        startedBy: "Started By",
        closedBy: "Closed By",
        startDate: "Start Date",
        closedDate: "Closed Date",
        discountPercentage: "Discount Percentage",
        discountAmount: "Discount Amount",
        totalValue: "Total Value",
        salesCommissionPercentage: "Sales Commission Percentage",
        salesCommissionAmount: "Sales Commission Amount",
        description: "Description",
        unknownClient: "Unknown Client",
        eg1000000: "e.g. 1000000",
        eg10: "e.g. 10",
        calculated: "Calculated",
        eg25: "e.g. 2.5",
        enterNotesAboutDeal: "Enter any notes about the deal...",
        // Users
        autoAssignment: "Auto Assignment",
        on: "On",
        off: "Off",
        viewUser: "View User", // Keep for backward compatibility
        createUser: "Create User", // Keep for backward compatibility
        editUser: "Edit User", // Keep for backward compatibility
        deleteUser: "Delete User", // Keep for backward compatibility
        viewEmployee: "View Employee",
        createEmployee: "Create Employee",
        editEmployee: "Edit Employee",
        deleteEmployee: "Delete Employee",
        noEmployeesFound: "No employees found",
        salesAssistant: "Sales Assistant",
        employee: "Employee",
        owner: "Owner",
        noPhoneNumber: "No phone number available",
        nameRequired: "Name is required",
        nameMinLength: "Name must be at least 2 characters",
        usernameRequired: "Username is required",
        usernameMinLength: "Username must be at least 3 characters",
        usernameInvalidChars: "Username can only contain letters, numbers, and underscores",
        emailRequired: "Email is required",
        passwordRequired: "Password is required",
        passwordMinLength: "Password must be at least 8 characters",
        passwordComplexity: "Password must contain at least one letter and one number",
        phoneRequired: "Phone is required",
        enterPhone: "Enter phone number",
        invalidPhone: "Invalid phone number format",
        invalidPhoneFormat: "Phone number must include country code (e.g., +966...)",
        invalidPhoneLength: "Phone number length is invalid",
        roleRequired: "Role is required",
        invalidEmail: "Invalid email format",
        userCreatedSuccessfully: "User created successfully!", // Keep for backward compatibility
        userUpdatedSuccessfully: "User updated successfully!", // Keep for backward compatibility
        errorCreatingUser: "Failed to create user. Please try again.", // Keep for backward compatibility
        errorUpdatingUser: "Failed to update user. Please try again.", // Keep for backward compatibility
        employeeCreatedSuccessfully: "Employee created successfully!",
        employeeUpdatedSuccessfully: "Employee updated successfully!",
        errorCreatingEmployee: "Failed to create employee. Please try again.",
        errorUpdatingEmployee: "Failed to update employee. Please try again.",
        emailAlreadyExists: "This email is already registered",
        usernameAlreadyExists: "This username is already taken",
        phoneAlreadyExists: "This phone number is already registered",
        // Campaigns
        addCampaign: "Add Campaign",
        isActive: "Is Active",
        yes: "Yes",
        no: "No",
        noResultsFound: "No results found.",
        noUnitsFound: "No units found.",
        noProjectsFound: "No projects found.",
        noDevelopersFound: "No developers found.",
        // Filter Drawers
        filterActivities: "Filter Activities",
        activityInfo: "Activity Information",
        leadType: "Lead Type",
        timePeriod: "Time Period",
        time: "Time",
        activityDateFrom: "Activity Date (From)",
        activityDateTo: "Activity Date (To)",
        filterCampaigns: "Filter Campaigns",
        campaignInfo: "Campaign Information",
        campaignCreatedAtFrom: "Campaign Created At (From)",
        campaignCreatedAtTo: "Campaign Created At (To)",
        searchByNameOrCode: "Search by name or code",
        filterProjects: "Filter Projects",
        projectInfo: "Project Information",
        filterServicePackages: "Filter Service Packages",
        packageInfo: "Package Information",
        priceRangeStart: "Price Range Start",
        priceRangeEnd: "Price Range End",
        filterProducts: "Filter Products",
        productInfo: "Product Information",
        stockRangeStart: "Stock Range Start",
        stockRangeEnd: "Stock Range End",
        filterServices: "Filter Services",
        serviceInfo: "Service Information",
        filterServiceProviders: "Filter Service Providers",
        providerInfo: "Provider Information",
        filterSuppliers: "Filter Suppliers",
        supplierInfo: "Supplier Information",
        searchByClientNameOrId: "Search by client name or deal ID",
        leadCreatedAtRange: "Lead Created At Range",
        filterProductCategories: "Filter Product Categories",
        filterDevelopers: "Filter Developers",
        filterOwners: "Filter Owners",
        ownerInfo: "Owner Information",
        unitInfo: "Unit Information",
        valueRangeStart: "Value Range Start",
        valueRangeEnd: "Value Range End",
        // Todos
        addTodo: "Add Todo",
        thisWeek: "This Week",
        noTasksForDate: "No tasks for",
        failedToCompleteTodo: "Failed to complete todo. Please try again.",
        completed: "Completed",
        // Reports
        allTeams: "All Teams",
        selectFiltersPrompt: "Select filters to view the report.",
        totalCalls: "Total calls",
        answered: "Answered",
        notAnswered: "Not Answered",
        // Integrations
        integration: "Integration",
        addNewAccount: "Add New Account",
        disconnect: "Disconnect",
        noAccountsConnected: "No accounts connected",
        connectAccountPrompt: "Click 'Add New Account' to connect your page and start capturing leads.",
        // General
        status: "Status",
        code: "Code",
        budget: "Budget",
        role: "Role",
        email: "Email",
        unit: "Unit",
        // Settings
        leadAssignmentSettings: "Lead Assignment Settings",
        autoRotation: "Enable Auto Rotation for Delayed Leads",
        autoRotationDesc: "When enabled, the system automatically reassigns leads that have not been attended to within a specified time.",
        reminderDelayTime: "Reminder Delay Time (Minutes)",
        reminderDelayTimeDesc: "This time determines how long to wait before a lead is marked as 'delayed'.",
        saveSettings: "Save Settings",
        channelAutomation: "Channel Automation",
        multiChannelTracking: "Enable Multi-Channel Lead Tracking",
        defaultChannel: "Default Channel",
        defaultChannelDesc: "Assign a channel to any new leads with an unknown source.",
        activeChannels: "Active Channels",
        addChannel: "Add Channel",
        channel: "Channel",
        addType: "Add Type",
        typeName: "Type Name",
        enterTypeName: "Enter type name",
        stageAutomation: "Stage Automation",
        autoStageAdvancement: "Enable Auto Stage Advancement",
        requireStageCompletion: "Require Stage Completion",
        leadStages: "Lead Stages",
        addStage: "Add Stage",
        stageName: "Stage Name",
        required: "Required",
        autoAdvance: "Auto Advance",
        statusConfiguration: "Status Configuration",
        enableCustomStatuses: "Enable Custom Statuses",
        requireStatusUpdates: "Require Status Updates",
        defaultActiveStatus: "Default Active Status",
        defaultActiveStatusDesc: "Set the default status for all new leads.",
        availableStatuses: "Available Statuses",
        addStatus: "Add Status",
        address: "Address",
        supplier: "Supplier",
        category: "Category",
        followUp: "Follow Up",
        closed: "Closed",
        // Modals & Drawers general
        submit: "Submit",
        cancel: "Cancel",
        reset: "Reset",
        applyFilters: "Apply Filters",
        edit: "Edit",
        confirmDelete: "Are you sure you want to delete this item? This action cannot be undone.",
        confirmDeleteWarning: "This action cannot be undone.",
        deleting: "Deleting...",
        // AddLeadModal
        addNewLead: "Add New Lead",
        clientName: "Client Name",
        enterClientName: "Enter client name",
        // FIX: Added missing translation key.
        enterBudget: "Enter budget",
        phoneNumber: "Phone Number",
        enterPrice: "Enter price",
        enterDuration: "e.g., 1 hour",
        enterCategory: "Enter category",
        assignedTo: "Assigned To",
        decisionMaker: "Decision Maker",
        influencer: "Influencer",
        fresh: "Fresh",
        cold: "Cold",
        high: "High",
        medium: "Medium",
        low: "Low",
        egFacebookAd: "e.g., Facebook Ad",
        // AddActionModal
        for: "for",
        stage: "Stage",
        untouched: "Untouched",
        touched: "Touched",
        following: "Following",
        noAnswer: "No Answer",
        outOfService: "Out Of Service",
        // Task Stages
        hold: "Hold",
        doneMeeting: "Done Meeting",
        followAfterMeeting: "Follow After Meeting",
        rescheduleMeeting: "Reschedule Meeting",
        cancellation: "Cancellation",
        notInterested: "Not Interested",
        whatsappPending: "WhatsApp Pending",
        broker: "Broker",
        resale: "Resale",
        // AddTodoModal
        deal: "Deal",
        selectDeal: "Select Deal",
        reminderDateAndTime: "Reminder Date & Time",
        enterNotes: "Enter notes...",
        loading: "Loading...",
        pleaseFillRequiredFields: "Please fill in required fields",
        failedToCreateTodo: "Failed to create todo. Please try again.",
        writeActionDetails: "Write details of the action (e.g., call summary)",
        reminderDate: "Reminder Date",
        stageUpdated: "Stage updated",
        // AssignLeadModal
        leadsCount: "Leads Count",
        selectEmployee: "Select Employee",
        // FilterDrawer
        filterLeads: "Filter Leads",
        teamLeader: "Team Leader",
        selectLeader: "Select leader",
        assigned: "Assigned",
        selectAssignedOrNot: "Select is assigned or not",
        unassigned: "Unassigned",
        selectUser: "Select user",
        selectLead: "Select Lead",
        selectAuthority: "Select authority",
        leadInfo: "Lead Info",
        selectProject: "Select project",
        selectCampaign: "Select campaign",
        selectChannel: "Select channel",
        qualified: "Qualified",
        unqualified: "Unqualified",
        cancelReasons: "Cancel Reasons",
        selectCancelReason: "Select cancel reason",
        budgetTooHigh: "Budget too high",
        currentStage: "Current Stage",
        selectStage: "Select stage",
        hasStages: "Has Stages",
        selectStages: "Select stages",
        selectPriority: "Select priority",
        excelFilenames: "Excel Filenames",
        selectExcel: "Select excel",
        budgetRangeStart: "Budget Range Start",
        eg500000: "e.g., 500000",
        budgetRangeEnd: "Budget Range End",
        delay: "Delay",
        delayedReminderLeads: "Delayed Reminder Leads",
        selectDelayedOrNot: "Select delayed or not",
        delayed: "Delayed",
        notDelayed: "Not Delayed",
        dateAddedRange: "Date Added Range",
        dateAssignedRange: "Date Assigned Range",
        lastActionRange: "Last Action Range",
        reminderDateRange: "Reminder Date Range",
        // UnitsFilterDrawer
        filterUnits: "Filter Units",
        filters: "Filters",
        filterTeamsReport: "Filter Teams Report",
        filterEmployeesReport: "Filter Employees Report",
        filterMarketingReport: "Filter Marketing Report",
        export: "Export",
        reportInfo: "Report Information",
        endDate: "End Date",
        team: "Team",
        selectBedrooms: "Select Bedrooms",
        selectBathrooms: "Select Bathrooms",
        selectType: "Select Type",
        apartment: "Apartment",
        villa: "Villa",
        finishingType: "Finishing type",
        selectFinishing: "Select Finishing",
        finished: "Finished",
        semiFinished: "Semi-Finished",
        selectCity: "Select City",
        selectDistrict: "Select District",
        selectZone: "Select Zone",
        eg2000000: "e.g., 2000000",
        sold: "Sold",
        // AddDeveloperModal
        addNewDeveloper: "Add New Developer",
        developerName: "Developer Name",
        enterDeveloperName: "Enter developer name",
        enterCode: "Enter code",
        // AddProjectModal
        addNewProject: "Add New Project",
        projectName: "Project Name",
        enterProjectName: "Enter project name",
        // AddUnitModal
        addNewUnit: "Add New Unit",
        unitCode: "Unit Code",
        enterUnitCode: "Enter unit code",
        // AddOwnerModal
        addNewOwner: "Add New Owner",
        ownerName: "Owner name",
        enterOwnerFullName: "Enter owner's full name",
        ownerCode: "Owner code",
        enterUniqueCode: "Enter a unique code",
        ownerPhone: "Owner phone",
        enterContactPhoneNumber: "Enter contact phone number",
        selectCityPlaceholder: "Select city...",
        riyadh: "Riyadh",
        jeddah: "Jeddah",
        dammam: "Dammam",
        ownerDistrict: "Owner district",
        enterSpecificDistrict: "Enter the specific district",
        // DealsFilterDrawer
        filterDeals: "Filter Deals",
        addedBy: "Added By",
        dealInfo: "Deal Info",
        selectStatus: "Select status",
        reservation: "Reservation",
        contracted: "Contracted",
        // closed: "Closed", // This key already exists
        selectMethod: "Select method",
        cash: "Cash",
        installment: "Installment",
        selectUnit: "Select unit",
        leadChannel: "Lead Channel",
        google: "Google",
        leadCampaign: "Lead Campaign",
        datesAndDuration: "Dates & Duration",
        dealCreatedAtRange: "Deal created At range",
        durationDays: "Duration (days)",
        eg30: "e.g. 30",
        // EditUserModal
        newUserPassword: "New Password",
        leaveBlankPassword: "Leave blank to keep current password",
        salesManager: "Sales Manager",
        salesAgent: "Sales Agent",
        saveChanges: "Save Changes",
        // DeleteUserModal
        confirmDeleteUser1: "Are you sure you want to delete the user", // Keep for backward compatibility
        confirmDeleteUser2: "? This action cannot be undone.", // Keep for backward compatibility
        confirmDeleteEmployee1: "Are you sure you want to delete the employee",
        confirmDeleteEmployee2: "? This action cannot be undone.",
        // AddCampaignModal
        addNewCampaign: "Add New Campaign",
        enterCampaignName: "Enter campaign name",
        enterCampaignCode: "Enter campaign code",
        enterCampaignBudget: "Enter campaign budget",
        // AddIntegrationAccountModal
        addNew: "Add New",
        account: "Account",
        accountName: "Account Name",
        enterAccountName: "Enter account name",
        accountLink: "Account Link",
        egSalesWhatsapp: "e.g., Sales WhatsApp",
        enterWhatsappNumber: "Enter WhatsApp number",
        connected: "Connected",
        disconnected: "Disconnected",
        // ChangePasswordModal
        changePassword: "Change Password",
        currentPassword: "Current Password",
        enterCurrentPassword: "Enter current password",
        newPassword: "New Password",
        enterNewPassword: "Enter new password",
        confirmNewPassword: "Confirm New Password",
        enterConfirmNewPassword: "Enter new password again",
        currentPasswordRequired: "Current password is required",
        newPasswordRequired: "New password is required",
        confirmPasswordRequired: "Confirm password is required",
        passwordsDoNotMatch: "Passwords do not match",
        newPasswordMustBeDifferent: "New password must be different from current password",
        passwordChangedSuccessfully: "Password changed successfully!",
        errorChangingPassword: "Error changing password",
        changing: "Changing...",
        // Profile
        profile: "Profile",
        profileSettings: "Profile Settings",
        siteCustomization: "Site Customization",
        primaryColor: "Primary Color",
        activeSubPageColor: "Active Sub-Page Color",
        siteLogo: "Site Logo",
        profilePicture: "Profile Picture",
        upload: "Upload",
        security: "Security",
        saveProfile: "Save Profile",
        emailVerified: "Email verified",
        emailNotVerified: "Email not verified. Please check your inbox for verification email.",
        // Delete modals
        deleteChannel: "Delete Channel",
        confirmDeleteChannel: "Are you sure you want to delete",
        deleteStage: "Delete Stage",
        confirmDeleteStage: "Are you sure you want to delete",
        deleteStatus: "Delete Status",
        confirmDeleteStatus: "Are you sure you want to delete",
        cannotDeleteDefault: "Cannot delete default status",
        // Registration
        register: "Register",
        dontHaveAccount: "Don't have an account?",
        forgotPassword: "Forgot Password?",
        alreadyHaveAccount: "Already have an account?",
        createAccount: "Create Your Account",
        registerDescription: "Start managing your business with our powerful CRM system. Get started in minutes.",
        createCompanyAccount: "Create your company account",
        registrationFailed: "Registration failed. Please try again.",
        networkError: "Network error: Unable to connect to the server. Please check your internet connection and ensure the API server is accessible.",
        companyInformation: "Company Information",
        companyName: "Company Name",
        enterCompanyName: "Enter company name",
        companyNameRequired: "Company name is required",
        companyDomain: "Company Domain",
        enterCompanyDomain: "e.g., example.com",
        companyDomainRequired: "Company domain is required",
        invalidDomain: "Invalid domain format",
        domainAlreadyExists: "Company domain already exists",
        domainHint: "This will be used as your company identifier",
        realEstate: "Real Estate",
        ownerInformation: "Owner Information",
        firstName: "First Name",
        enterFirstName: "Enter first name",
        firstNameRequired: "First name is required",
        lastName: "Last Name",
        enterLastName: "Enter last name",
        lastNameRequired: "Last name is required",
        enterEmail: "Enter email address",
        enterUsername: "Enter username",
        enterPassword: "Enter password",
        confirmPassword: "Confirm Password",
        selectPlan: "Select a Plan",
        planSelectionHint: "Choose the plan that fits your team. You can switch later and no payment details are required now.",
        billingCycle: "Billing cycle",
        monthly: "Monthly",
        yearly: "Yearly",
        loadingPlans: "Loading plans...",
        noPlansAvailable: "No paid plans are published yet. You can continue with the free trial.",
        freeTrial: "Free Trial",
        trialDescription: "14 days free trial, no credit card required",
        free: "Free",
        plansWillBeAdded: "Plans will be available after registration",
        planNoteNoPayment: "We activate your chosen plan immediately—upgrade or downgrade anytime from settings.",
        planDefaultDescription: "All CRM essentials included.",
        usersIncluded: "Users",
        clientsIncluded: "Clients",
        storageIncluded: "Storage",
        trialDaysLabel: "trial days",
        perMonth: "per month",
        perYear: "per year",
        planRequired: "Please select a plan to continue",
        passwordRequirements: "Use at least 8 characters, include letters and numbers, and avoid common passwords.",
        verifyEmailTitle: "Verify your email",
        verifyEmailDescription: "We sent a 6-digit code to your inbox. Enter it below to activate your account.",
        verificationSentTo: "Sent to",
        verificationExpiresAt: "Code expires at",
        verificationCodeLabel: "Verification code",
        verificationCodePlaceholder: "Enter 6-digit code",
        verificationSentMessage: "We sent a 6-digit code to your inbox. Enter it below to activate your account.",
        verificationSendFailed: "We couldn't send the verification email automatically. Please contact support or use the link inside the email when it arrives.",
        verificationEmailMissing: "Email is missing for verification.",
        verificationCodeRequired: "Please enter the verification code sent to your email.",
        verificationSuccess: "Email verified successfully! Redirecting you now...",
        verificationFailed: "Verification failed. Please try again.",
        verifyLater: "Verify later",
        verifyNow: "Verify email",
        verifyLaterHint: "If you choose \"Verify later\", you can still finish by clicking the verification link inside your inbox.",
        verifyingEmail: "Verifying your email address...",
        verifying: "Verifying...",
        verificationLinkInvalid: "Invalid verification link. Please check your email and try again.",
        emailVerifiedSuccessfully: "Your email has been verified successfully! You can now log in.",
        goToLogin: "Go to Login",
        goToDashboard: "Go to Dashboard",
        verificationHelpText: "If you continue to experience issues, please contact support or request a new verification email.",
        back: "Back",
        next: "Next",
        // Forgot Password
        forgotPasswordDescription: "No worries! Enter your email address and we'll send you a link to reset your password.",
        forgotPasswordSubtitle: "Enter your email address and we'll send you a reset link",
        passwordResetEmailSent: "If the email exists, a password reset link has been sent to your email address. Please check your inbox.",
        sendResetLink: "Send Reset Link",
        rememberPassword: "Remember your password?",
        pleaseEnterEmail: "Please enter your email address",
        invalidEmailFormat: "Please enter a valid email address",
        // Reset Password
        resetPassword: "Reset Password",
        resetPasswordDescription: "Enter your new password below to complete the reset process.",
        enterNewPasswordBelow: "Enter your new password below",
        passwordResetSuccess: "Password has been reset successfully! Redirecting to login...",
        pleaseEnterCodeOrToken: "Please enter the reset code or use the reset link",
        pleaseEnterNewPassword: "Please enter a new password",
        passwordTooShort: "Password must be at least 8 characters long",
        resetCode: "Reset Code",
        emailAddress: "Email",
        enterCodeFromEmail: "Enter the 6-digit code sent to your email",
        chooseResetMethod: "You can either click the link in your email or enter the code below:",
        continueWithCode: "Continue with Code",
        orClickLinkInEmail: "Or click the link in your email to continue",
        pleaseEnterCode: "Please enter the reset code",
        codeMustBe6Digits: "Code must be 6 digits",
        usingCodeToReset: "Using code to reset password",
        // Two Factor Authentication
        twoFactorAuth: "Two-Factor Authentication",
        twoFactorAuthTitle: "Two-Factor Authentication",
        twoFactorAuthDescription: "To ensure your account security, please enter the two-factor authentication code sent to your email",
        enter2FACode: "Enter the 6-digit two-factor authentication code",
        twoFactorCodeLabel: "Two-Factor Authentication Code",
        twoFactorCodePlaceholder: "000000",
        verify: "Verify",
        didntReceiveCode: "Didn't receive the code?",
        resendCode: "Resend Code",
        resendCodeCountdown: "Resend Code ({countdown} seconds)",
        backToLogin: "Back to Login",
        twoFactorCodeSent: "Two-factor authentication code has been sent to your email",
        pleaseEnter2FACode: "Please enter the 6-digit two-factor authentication code",
        twoFactorCodeInvalid: "Invalid two-factor authentication code",
        twoFactorCodeExpired: "Two-factor authentication code has expired. Please request a new one",
        twoFactorCodeRequired: "Please enter the two-factor authentication code",
        twoFactorCodeLengthError: "The code must be 6 digits",
        twoFactorAuthFailed: "Failed to verify two-factor authentication code",
        twoFactorAuthRequestFailed: "Failed to request two-factor authentication code",
        // Payment
        paymentSubscriptionIdRequired: "Subscription ID is required",
        paymentRedirectError: "Failed to get payment URL",
        paymentInitError: "Failed to initialize payment",
        paymentRedirecting: "Redirecting to payment gateway...",
        paymentError: "Payment Error",
        backToRegistration: "Back to Registration",
        paymentProcessing: "Processing your payment...",
        paymentSuccess: "Payment Successful!",
        paymentSuccessMessage: "Your payment has been processed successfully. Your account is now active.",
        redirectingToDashboard: "Redirecting you to your dashboard...",
        paymentSuccessNote: "You will be automatically redirected in a few seconds",
        paymentSuccessNoData: "Payment successful but user data not found. Please login.",
        paymentSuccessError: "Error processing payment success",
        paymentPending: "Payment is still being processed. Please wait a moment and refresh.",
        noActiveSubscription: "Your subscription is not active. Please contact support or complete your payment to access the system.",
        noActiveSubscriptionBeforeLink: "Your subscription is not active. Please contact support or ",
        noActiveSubscriptionAfterLink: " to access the system.",
        completePayment: "complete your payment",
        completePaymentViaPaytabs: "Complete Payment via Paytabs",
    },
    ar: {
        hello: "أهلاً بك! 👋",
        welcomeBack: "مرحبا بعودتك!",
        signInToContinue: "سجل الدخول للمتابعة وإدارة علاقات عملائك بكفاءة.",
        crmWelcome: "مستقبل إدارة علاقات العملاء.",
        crmDescription: "أتمتة المهام المتكررة، تعزيز الإنتاجية، وتحسين سير عملك مع نظامنا البديهي لإدارة علاقات العملاء.",
        username: "اسم المستخدم",
        usernameOrEmail: "اسم المستخدم أو البريد الإلكتروني",
        password: "كلمة المرور",
        signIn: "تسجيل الدخول",
        pleaseEnterCredentials: "الرجاء إدخال اسم المستخدم وكلمة المرور",
        invalidCredentials: "اسم المستخدم أو كلمة المرور غير صحيحة",
        loginErrorNoActiveAccount: "لم يتم العثور على حساب نشط بالبيانات المقدمة",
        loginErrorUnableToLogin: "تعذر تسجيل الدخول بالبيانات المقدمة",
        loginErrorAccountInactive: "الحساب غير نشط",
        loginErrorInvalidCredentials: "اسم المستخدم أو كلمة المرور غير صحيحة",
        search: "بحث",
        searchEllipsis: "بحث...",
        all: "الكل",
        user: "المستخدم",
        // Sidebar
        dashboard: "لوحة التحكم",
        leads: "العملاء المحتملون",
        allLeads: "كل العملاء",
        freshLeads: "عملاء جدد",
        coldLeads: "عملاء باردون",
        myLeads: "عملائي",
        rotatedLeads: "عملاء معاد توجيههم",
        activities: "الأنشطة",
        inventory: "المخزون",
        properties: "العقارات",
        owners: "المالك",
        deals: "الصفقات",
        users: "المستخدمون", // Keep for backward compatibility
        employees: "الموظفون",
        marketing: "التسويق",
        campaigns: "الحملات",
        // FIX: Added missing translation key.
        campaign: "الحملة",
        todos: "المهام",
        reports: "التقارير",
        teamsReport: "تقرير الفرق",
        employeesReport: "تقرير الموظفين",
        marketingReport: "تقرير التسويق",
        integrations: "التكاملات",
        meta: "ميتا",
        facebook: "فيسبوك", // Keep for backward compatibility with data
        tikTok: "تيك توك",
        whatsApp: "واتساب",
        // FIX: Added missing translation key.
        website: "الموقع الإلكتروني",
        settings: "الإعدادات",
        channels: "القنوات",
        stages: "المراحل",
        statuses: "الحالات",
        logout: "تسجيل الخروج",
        logoutConfirmTitle: "تأكيد تسجيل الخروج",
        logoutConfirmMessage: "هل أنت متأكد أنك تريد تسجيل الخروج؟",
        // Dashboard
        todayNewLeads: "عملاء محتملون جدد اليوم",
        todayTouchedLeads: "عملاء تم التواصل معهم اليوم",
        todayUntouchedLeads: "عملاء لم يتم التواصل معهم اليوم",
        delayedLeads: "عملاء متأخرون",
        weekLeadsReport: "تقرير العملاء الأسبوعي",
        last7DaysPerformance: "أداء آخر 7 أيام",
        stagesReport: "تقرير المراحل",
        distributionByStage: "التوزيع حسب المرحلة",
        topUsers: "أفضل المستخدمين",
        mostActivePerformers: "الأكثر نشاطاً",
        latestFeedbacks: "آخر الملاحظات",
        recentActivityUpdates: "تحديثات الأنشطة الأخيرة",
        noDataAvailable: "لا توجد بيانات متاحة",
        noStageDataAvailable: "لا توجد بيانات مراحل متاحة",
        noUserActivityData: "لا توجد بيانات نشاط المستخدمين",
        noRecentFeedbackAvailable: "لا توجد ملاحظات حديثة متاحة",
        noNotes: "لا توجد ملاحظات",
        totalLeads: "إجمالي العملاء",
        totalDeals: "إجمالي الصفقات",
        activeTodos: "المهام النشطة",
        completedDeals: "الصفقات المكتملة",
        // Leads
        filter: "تصفية",
        addLead: "إضافة عميل",
        assignLead: "إسناد عميل",
        confirmAssignLeads: "تأكيد الإسناد",
        confirmAssignLeadsMessage: "هل أنت متأكد من أنك تريد إسناد",
        confirmAssignLeadsMessage2: "عميل/عملاء إلى",
        confirmAssign: "تأكيد",
        assigning: "جاري الإسناد...",
        assignLeadsError: "فشل إسناد العملاء المحتملين. يرجى المحاولة مرة أخرى.",
        assignToMe: "إسناد لنفسي",
        confirmAssignToMe: "تأكيد الإسناد",
        confirmAssignToMeMessage: "هل أنت متأكد من أنك تريد إسناد هذا العميل المحتمل لنفسك؟",
        assignLeadError: "فشل إسناد العميل المحتمل. يرجى المحاولة مرة أخرى.",
        noUserSelected: "لم يتم اختيار مستخدم",
        name: "الاسم",
        phone: "الهاتف",
        actions: "إجراءات",
        lastFeedback: "آخر ملاحظة",
        notes: "ملاحظات",
        lastStage: "آخر مرحلة",
        reminder: "تذكير",
        view: "عرض",
        add_action: "إضافة إجراء",
        // View Lead
        unassign: "إلغاء الإسناد",
        addDeal: "إضافة صفقة",
        editClient: "تعديل العميل",
        details: "التفاصيل",
        communicationWay: "طريقة التواصل",
        authority: "الصلاحية",
        priority: "الأولوية",
        dates: "التواريخ",
        createdAt: "تاريخ الإنشاء",
        timeline: "السجل الزمني",
        // Activities
        allUsers: "كل المستخدمين",
        today: "اليوم",
        yesterday: "الأمس",
        last7Days: "آخر 7 أيام",
        thisMonth: "هذا الشهر",
        allLeadsType: "كل أنواع العملاء",
        freshLead: "عميل جديد",
        coldLead: "عميل بارد",
        call: "مكالمة",
        meeting: "اجتماع",
        whatsapp: "واتساب",
        note: "ملاحظة",
        lead: "العميل",
        type: "النوع",
        date: "التاريخ",
        noActivitiesFound: "لم يتم العثور على أنشطة للمرشحات المحددة.",
        // Properties
        createNew: "إنشاء جديد",
        addDeveloper: "إضافة مطور",
        addProject: "إضافة مشروع",
        addUnit: "إضافة وحدة",
        // Services
        services: "الخدمات",
        servicePackages: "باقات الخدمات",
        serviceProviders: "مقدمي الخدمات",
        addService: "إضافة خدمة",
        editService: "تعديل خدمة",
        deleteService: "حذف خدمة",
        confirmDeleteService: "هل أنت متأكد أنك تريد حذف",
        addServicePackage: "إضافة باقة خدمة",
        editServicePackage: "تعديل باقة خدمة",
        deleteServicePackage: "حذف باقة خدمة",
        confirmDeleteServicePackage: "هل أنت متأكد أنك تريد حذف",
        addServiceProvider: "إضافة مقدم خدمة",
        editServiceProvider: "تعديل مقدم خدمة",
        deleteServiceProvider: "حذف مقدم خدمة",
        confirmDeleteServiceProvider: "هل أنت متأكد أنك تريد حذف",
        enterServiceName: "أدخل اسم الخدمة",
        enterServiceDescription: "أدخل وصف الخدمة",
        enterPackageName: "أدخل اسم الباقة",
        enterPackageDescription: "أدخل وصف الباقة",
        enterProviderName: "أدخل اسم مقدم الخدمة",
        enterPhoneNumber: "أدخل رقم الهاتف",
        enterSpecialization: "أدخل التخصص",
        enterContactPerson: "أدخل اسم المسؤول",
        enterRating: "أدخل التقييم (0-5)",
        selectProvider: "اختر مقدم الخدمة (اختياري)",
        noServicesAvailable: "لا توجد خدمات متاحة",
        provider: "مقدم الخدمة",
        duration: "المدة (ساعة)",
        rating: "التقييم",
        failedToCreateService: "فشل إنشاء الخدمة. يرجى المحاولة مرة أخرى.",
        failedToUpdateService: "فشل تحديث الخدمة. يرجى المحاولة مرة أخرى.",
        failedToCreateServicePackage: "فشل إنشاء باقة الخدمة. يرجى المحاولة مرة أخرى.",
        failedToUpdateServicePackage: "فشل تحديث باقة الخدمة. يرجى المحاولة مرة أخرى.",
        failedToCreateServiceProvider: "فشل إنشاء مقدم الخدمة. يرجى المحاولة مرة أخرى.",
        failedToUpdateServiceProvider: "فشل تحديث مقدم الخدمة. يرجى المحاولة مرة أخرى.",
        // Products
        products: "المنتجات",
        productCategories: "فئات المنتجات",
        suppliers: "الموردون",
        addProduct: "إضافة منتج",
        editProduct: "تعديل منتج",
        deleteProduct: "حذف منتج",
        confirmDeleteProduct: "هل أنت متأكد أنك تريد حذف",
        addProductCategory: "إضافة فئة منتج",
        editProductCategory: "تعديل فئة منتج",
        deleteProductCategory: "حذف فئة منتج",
        confirmDeleteProductCategory: "هل أنت متأكد أنك تريد حذف",
        addSupplier: "إضافة مورد",
        editSupplier: "تعديل مورد",
        deleteSupplier: "حذف مورد",
        confirmDeleteSupplier: "هل أنت متأكد أنك تريد حذف",
        enterProductName: "أدخل اسم المنتج",
        enterProductDescription: "أدخل وصف المنتج",
        enterCost: "أدخل التكلفة",
        enterStock: "أدخل المخزون",
        selectCategory: "اختر الفئة",
        selectSupplier: "اختر المورد (اختياري)",
        enterSKU: "أدخل رمز المنتج",
        enterCategoryName: "أدخل اسم الفئة",
        enterCategoryDescription: "أدخل وصف الفئة",
        selectParentCategory: "اختر الفئة الرئيسية (اختياري)",
        enterSupplierName: "أدخل اسم المورد",
        enterAddress: "أدخل العنوان",
        fillRequiredFields: "الرجاء ملء الحقول المطلوبة",
        failedToCreateProduct: "فشل إنشاء المنتج. يرجى المحاولة مرة أخرى.",
        failedToUpdateProduct: "فشل تحديث المنتج. يرجى المحاولة مرة أخرى.",
        failedToCreateProductCategory: "فشل إنشاء فئة المنتج. يرجى المحاولة مرة أخرى.",
        failedToUpdateProductCategory: "فشل تحديث فئة المنتج. يرجى المحاولة مرة أخرى.",
        failedToCreateSupplier: "فشل إنشاء المورد. يرجى المحاولة مرة أخرى.",
        failedToUpdateSupplier: "فشل تحديث المورد. يرجى المحاولة مرة أخرى.",
        cost: "التكلفة",
        stock: "المخزون",
        sku: "رمز المنتج",
        contactPerson: "الشخص المسؤول",
        specialization: "التخصص",
        realEstateOnly: "هذه الصفحة متاحة فقط لشركات العقارات.",
        servicesOnly: "هذه الصفحة متاحة فقط لشركات الخدمات.",
        productsOnly: "هذه الصفحة متاحة فقط لشركات المنتجات.",
        active: "نشط",
        inactive: "غير نشط",
        units: "الوحدات",
        projects: "المشاريع",
        developers: "المطورون",
        searchUnits: "بحث في الوحدات",
        searchProjects: "بحث في المشاريع",
        searchDevelopers: "بحث في المطورين",
        noUnitsFound: "لم يتم العثور على وحدات.",
        noProjectsFound: "لم يتم العثور على مشاريع.",
        noDevelopersFound: "لم يتم العثور على مطورين.",
        logo: "الشعار",
        developer: "المطور",
        city: "المدينة",
        paymentMethod: "طريقة الدفع",
        update: "تحديث",
        delete: "حذف",
        bedrooms: "غرف النوم",
        // FIX: Added missing translation key.
        bathrooms: "الحمامات",
        price: "السعر",
        // Owners
        addOwner: "إضافة مالك",
        district: "الحي",
        // FIX: Added missing translation key.
        zone: "المنطقة",
        noOwnersFound: "لم يتم العثور على ملاك.",
        // Deals
        searchDeals: "بحث في الصفقات",
        createDeal: "إنشاء صفقة",
        dealId: "المعرف",
        value: "القيمة",
        noDealsFound: "لم يتم العثور على صفقات.",
        // Create Deal
        createNewDeal: "إنشاء صفقة جديدة",
        dealInformation: "معلومات الصفقة",
        project: "المشروع",
        startedBy: "بدأت بواسطة",
        closedBy: "أغلقت بواسطة",
        startDate: "تاريخ البدء",
        closedDate: "تاريخ الإغلاق",
        discountPercentage: "نسبة الخصم",
        discountAmount: "مبلغ الخصم",
        totalValue: "القيمة الإجمالية",
        salesCommissionPercentage: "نسبة عمولة المبيعات",
        salesCommissionAmount: "مبلغ عمولة المبيعات",
        description: "الوصف",
        unknownClient: "عميل غير معروف",
        eg1000000: "مثال: 1000000",
        eg10: "مثال: 10",
        calculated: "محسوب تلقائياً",
        eg25: "مثال: 2.5",
        enterNotesAboutDeal: "أدخل أي ملاحظات حول الصفقة...",
        // Users
        autoAssignment: "الإسناد التلقائي",
        on: "مفعل",
        off: "معطل",
        viewUser: "عرض المستخدم", // Keep for backward compatibility
        createUser: "إنشاء مستخدم", // Keep for backward compatibility
        editUser: "تعديل المستخدم", // Keep for backward compatibility
        deleteUser: "حذف المستخدم", // Keep for backward compatibility
        viewEmployee: "عرض الموظف",
        createEmployee: "إنشاء موظف",
        editEmployee: "تعديل الموظف",
        deleteEmployee: "حذف الموظف",
        noEmployeesFound: "لا يوجد موظفون",
        salesAssistant: "مساعد مبيعات",
        employee: "موظف",
        owner: "المالك",
        noPhoneNumber: "لا يوجد رقم هاتف متاح",
        nameRequired: "الاسم مطلوب",
        nameMinLength: "يجب أن يكون الاسم حرفين على الأقل",
        usernameRequired: "اسم المستخدم مطلوب",
        usernameMinLength: "يجب أن يكون اسم المستخدم 3 أحرف على الأقل",
        usernameInvalidChars: "يمكن أن يحتوي اسم المستخدم على الأحرف والأرقام والشرطة السفلية فقط",
        emailRequired: "البريد الإلكتروني مطلوب",
        passwordRequired: "كلمة المرور مطلوبة",
        passwordMinLength: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
        passwordComplexity: "يجب أن تحتوي كلمة المرور على حرف واحد ورقم واحد على الأقل",
        phoneRequired: "رقم الهاتف مطلوب",
        enterPhone: "أدخل رقم الهاتف",
        invalidPhone: "صيغة رقم الهاتف غير صحيحة",
        invalidPhoneFormat: "يجب أن يتضمن رقم الهاتف رمز الدولة (مثل: +966...)",
        invalidPhoneLength: "طول رقم الهاتف غير صحيح",
        roleRequired: "الدور مطلوب",
        invalidEmail: "صيغة البريد الإلكتروني غير صحيحة",
        userCreatedSuccessfully: "تم إنشاء المستخدم بنجاح!", // Keep for backward compatibility
        userUpdatedSuccessfully: "تم تحديث المستخدم بنجاح!", // Keep for backward compatibility
        errorCreatingUser: "فشل إنشاء المستخدم. يرجى المحاولة مرة أخرى.", // Keep for backward compatibility
        errorUpdatingUser: "فشل تحديث المستخدم. يرجى المحاولة مرة أخرى.", // Keep for backward compatibility
        employeeCreatedSuccessfully: "تم إنشاء الموظف بنجاح!",
        employeeUpdatedSuccessfully: "تم تحديث الموظف بنجاح!",
        errorCreatingEmployee: "فشل إنشاء الموظف. يرجى المحاولة مرة أخرى.",
        errorUpdatingEmployee: "فشل تحديث الموظف. يرجى المحاولة مرة أخرى.",
        emailAlreadyExists: "هذا البريد الإلكتروني مسجل بالفعل",
        usernameAlreadyExists: "اسم المستخدم هذا مستخدم بالفعل",
        phoneAlreadyExists: "رقم الهاتف هذا مسجل بالفعل",
        // Campaigns
        addCampaign: "إضافة حملة",
        isActive: "نشطة",
        yes: "نعم",
        no: "لا",
        noResultsFound: "لم يتم العثور على نتائج.",
        // Todos
        addTodo: "إضافة مهمة",
        thisWeek: "هذا الأسبوع",
        noTasksForDate: "لا توجد مهام بتاريخ",
        failedToCompleteTodo: "فشل إكمال المهمة. يرجى المحاولة مرة أخرى.",
        completed: "مكتمل",
        // Reports
        allTeams: "كل الفرق",
        selectFiltersPrompt: "اختر مرشحات لعرض التقرير.",
        totalCalls: "إجمالي المكالمات",
        answered: "تم الرد عليها",
        notAnswered: "لم يتم الرد عليها",
        // Integrations
        integration: "التكامل",
        addNewAccount: "إضافة حساب جديد",
        disconnect: "قطع الاتصال",
        noAccountsConnected: "لا توجد حسابات متصلة",
        connectAccountPrompt: "انقر فوق 'إضافة حساب جديد' لتوصيل صفحتك والبدء في التقاط العملاء المحتملين.",
        // General
        status: "الحالة",
        code: "الرمز",
        budget: "الميزانية",
        role: "الدور",
        email: "البريد الإلكتروني",
        unit: "الوحدة",
        // Settings
        leadAssignmentSettings: "إعدادات إسناد العملاء",
        autoRotation: "تمكين التدوير التلقائي للعملاء المتأخرين",
        autoRotationDesc: "عند التمكين، يقوم النظام تلقائيًا بإعادة تعيين العملاء الذين لم تتم متابعتهم خلال وقت محدد.",
        reminderDelayTime: "وقت تأخير التذكير (بالدقائق)",
        reminderDelayTimeDesc: "يحدد هذا الوقت مدة الانتظار قبل تمييز العميل بأنه 'متأخر'.",
        saveSettings: "حفظ الإعدادات",
        channelAutomation: "أتمتة القنوات",
        multiChannelTracking: "تمكين تتبع العملاء متعددي القنوات",
        defaultChannel: "القناة الافتراضية",
        defaultChannelDesc: "تعيين قناة لأي عملاء جدد بمصدر غير معروف.",
        activeChannels: "القنوات النشطة",
        addChannel: "إضافة قناة",
        channel: "القناة",
        addType: "إضافة نوع",
        typeName: "اسم النوع",
        enterTypeName: "أدخل اسم النوع",
        stageAutomation: "أتمتة المراحل",
        autoStageAdvancement: "تمكين التقدم التلقائي للمرحلة",
        requireStageCompletion: "طلب إكمال المرحلة",
        leadStages: "مراحل العملاء",
        addStage: "إضافة مرحلة",
        stageName: "اسم المرحلة",
        required: "مطلوب",
        autoAdvance: "تقدم تلقائي",
        statusConfiguration: "تكوين الحالة",
        enableCustomStatuses: "تمكين الحالات المخصصة",
        requireStatusUpdates: "طلب تحديثات الحالة",
        defaultActiveStatus: "الحالة النشطة الافتراضية",
        defaultActiveStatusDesc: "تعيين الحالة الافتراضية لجميع العملاء الجدد.",
        availableStatuses: "الحالات المتاحة",
        addStatus: "إضافة حالة",
        supplier: "المورد",
        address: "العنوان",
        category: "الفئة",
        followUp: "متابعة",
        closed: "مغلق",
        // Modals & Drawers general
        submit: "إرسال",
        cancel: "إلغاء",
        reset: "إعادة تعيين",
        applyFilters: "تطبيق الفلاتر",
        edit: "تعديل",
        confirmDelete: "هل أنت متأكد أنك تريد حذف هذا العنصر؟ لا يمكن التراجع عن هذا الإجراء.",
        confirmDeleteWarning: "لا يمكن التراجع عن هذا الإجراء.",
        deleting: "جاري الحذف...",
        // AddLeadModal
        addNewLead: "إضافة عميل جديد",
        clientName: "اسم العميل",
        enterClientName: "أدخل اسم العميل",
        // FIX: Added missing translation key.
        enterBudget: "أدخل الميزانية",
        enterPrice: "أدخل السعر",
        enterDuration: "مثال: ساعة واحدة",
        enterCategory: "أدخل الفئة",
        assignedTo: "مسند إلى",
        decisionMaker: "صاحب القرار",
        influencer: "مؤثر",
        fresh: "جديد",
        cold: "بارد",
        high: "مرتفع",
        medium: "متوسط",
        low: "منخفض",
        egFacebookAd: "مثال: إعلان فيسبوك",
        // AddActionModal
        for: "لـ",
        stage: "المرحلة",
        untouched: "لم يلمس",
        touched: "تم اللمس",
        following: "متابعة",
        noAnswer: "لا يوجد رد",
        outOfService: "خارج الخدمة",
        // Task Stages
        hold: "انتظار",
        doneMeeting: "تم الاجتماع",
        followAfterMeeting: "متابعة بعد الاجتماع",
        rescheduleMeeting: "إعادة جدولة الاجتماع",
        cancellation: "إلغاء",
        notInterested: "غير مهتم",
        whatsappPending: "واتساب معلق",
        broker: "وسيط",
        resale: "إعادة بيع",
        // AddTodoModal
        deal: "الصفقة",
        selectDeal: "اختر الصفقة",
        reminderDateAndTime: "تاريخ ووقت التذكير",
        enterNotes: "أدخل الملاحظات...",
        loading: "جاري التحميل...",
        pleaseFillRequiredFields: "الرجاء ملء الحقول المطلوبة",
        failedToCreateTodo: "فشل إنشاء المهمة. يرجى المحاولة مرة أخرى.",
        writeActionDetails: "اكتب تفاصيل الإجراء (مثل ملخص المكالمة)",
        reminderDate: "تاريخ التذكير",
        stageUpdated: "تم تحديث المرحلة",
        // AssignLeadModal
        leadsCount: "عدد العملاء",
        selectEmployee: "اختر موظف",
        // FilterDrawer
        filterLeads: "تصفية العملاء",
        teamLeader: "قائد الفريق",
        selectLeader: "اختر قائد",
        assigned: "مسند",
        selectAssignedOrNot: "اختر مسند أم لا",
        unassigned: "غير مسند",
        selectUser: "اختر مستخدم",
        selectLead: "اختر العميل",
        selectAuthority: "اختر الصلاحية",
        leadInfo: "معلومات العميل",
        selectProject: "اختر مشروع",
        selectCampaign: "اختر حملة",
        selectChannel: "اختر قناة",
        qualified: "مؤهل",
        unqualified: "غير مؤهل",
        cancelReasons: "أسباب الإلغاء",
        selectCancelReason: "اختر سبب الإلغاء",
        budgetTooHigh: "الميزانية مرتفعة جدا",
        currentStage: "المرحلة الحالية",
        selectStage: "اختر مرحلة",
        hasStages: "لديه مراحل",
        selectStages: "اختر مراحل",
        selectPriority: "اختر الأولوية",
        excelFilenames: "أسماء ملفات إكسل",
        selectExcel: "اختر ملف إكسل",
        budgetRangeStart: "بداية نطاق الميزانية",
        eg500000: "مثال: 500000",
        budgetRangeEnd: "نهاية نطاق الميزانية",
        delay: "تأخير",
        delayedReminderLeads: "عملاء بتذكير متأخر",
        selectDelayedOrNot: "اختر متأخر أم لا",
        delayed: "متأخر",
        notDelayed: "غير متأخر",
        dateAddedRange: "نطاق تاريخ الإضافة",
        dateAssignedRange: "نطاق تاريخ الإسناد",
        lastActionRange: "نطاق آخر إجراء",
        reminderDateRange: "نطاق تاريخ التذكير",
        // UnitsFilterDrawer
        filterUnits: "تصفية الوحدات",
        filters: "الفلاتر",
        filterTeamsReport: "تصفية تقرير الفرق",
        filterEmployeesReport: "تصفية تقرير الموظفين",
        filterMarketingReport: "تصفية تقرير التسويق",
        export: "تصدير",
        reportInfo: "معلومات التقرير",
        endDate: "تاريخ الانتهاء",
        team: "الفريق",
        selectBedrooms: "اختر عدد غرف النوم",
        selectBathrooms: "اختر عدد الحمامات",
        selectType: "اختر النوع",
        apartment: "شقة",
        villa: "فيلا",
        finishingType: "نوع التشطيب",
        selectFinishing: "اختر التشطيب",
        finished: "مشطب",
        semiFinished: "نصف تشطيب",
        selectCity: "اختر المدينة",
        selectDistrict: "اختر الحي",
        selectZone: "اختر المنطقة",
        eg2000000: "مثال: 2000000",
        sold: "مباع",
        // AddDeveloperModal
        addNewDeveloper: "إضافة مطور جديد",
        developerName: "اسم المطور",
        enterDeveloperName: "أدخل اسم المطور",
        enterCode: "أدخل الرمز",
        // AddProjectModal
        addNewProject: "إضافة مشروع جديد",
        projectName: "اسم المشروع",
        enterProjectName: "أدخل اسم المشروع",
        // AddUnitModal
        addNewUnit: "إضافة وحدة جديدة",
        unitCode: "رمز الوحدة",
        enterUnitCode: "أدخل رمز الوحدة",
        // AddOwnerModal
        addNewOwner: "إضافة مالك جديد",
        ownerName: "اسم المالك",
        enterOwnerFullName: "أدخل اسم المالك الكامل",
        ownerCode: "رمز المالك",
        enterUniqueCode: "أدخل رمزًا فريدًا",
        ownerPhone: "هاتف المالك",
        enterContactPhoneNumber: "أدخل رقم هاتف الاتصال",
        selectCityPlaceholder: "اختر مدينة...",
        riyadh: "الرياض",
        jeddah: "جدة",
        dammam: "الدمام",
        ownerDistrict: "حي المالك",
        enterSpecificDistrict: "أدخل الحي المحدد",
        // DealsFilterDrawer
        filterDeals: "تصفية الصفقات",
        addedBy: "أضيف بواسطة",
        dealInfo: "معلومات الصفقة",
        selectStatus: "اختر الحالة",
        reservation: "حجز",
        contracted: "تم التعاقد",
        // closed: "مغلق", // This key already exists
        selectMethod: "اختر الطريقة",
        cash: "نقدي",
        installment: "تقسيط",
        selectUnit: "اختر وحدة",
        leadChannel: "قناة العميل",
        google: "جوجل",
        leadCampaign: "حملة العميل",
        datesAndDuration: "التواريخ والمدة",
        leadCreatedAtRange: "نطاق تاريخ إنشاء العميل",
        dealCreatedAtRange: "نطاق تاريخ إنشاء الصفقة",
        durationDays: "المدة (أيام)",
        eg30: "مثال: 30",
        // EditUserModal
        newUserPassword: "كلمة المرور الجديدة",
        leaveBlankPassword: "اتركها فارغة للحفاظ على كلمة المرور الحالية",
        salesManager: "مدير مبيعات",
        salesAgent: "مندوب مبيعات",
        saveChanges: "حفظ التغييرات",
        // DeleteUserModal
        confirmDeleteUser1: "هل أنت متأكد أنك تريد حذف المستخدم", // Keep for backward compatibility
        confirmDeleteUser2: "؟ لا يمكن التراجع عن هذا الإجراء.", // Keep for backward compatibility
        confirmDeleteEmployee1: "هل أنت متأكد أنك تريد حذف الموظف",
        confirmDeleteEmployee2: "؟ لا يمكن التراجع عن هذا الإجراء.",
        // AddCampaignModal
        addNewCampaign: "إضافة حملة جديدة",
        enterCampaignName: "أدخل اسم الحملة",
        enterCampaignCode: "أدخل رمز الحملة",
        enterCampaignBudget: "أدخل ميزانية الحملة",
        // AddIntegrationAccountModal
        addNew: "Add New",
        account: "حساب",
        accountName: "اسم الحساب",
        enterAccountName: "أدخل اسم الحساب",
        accountLink: "رابط الحساب",
        egSalesWhatsapp: "مثال: واتساب المبيعات",
        phoneNumber: "رقم الهاتف",
        enterWhatsappNumber: "أدخل رقم الواتساب",
        connected: "متصل",
        disconnected: "غير متصل",
        // ChangePasswordModal
        changePassword: "تغيير كلمة المرور",
        currentPassword: "كلمة المرور الحالية",
        enterCurrentPassword: "أدخل كلمة المرور الحالية",
        newPassword: "كلمة المرور الجديدة",
        enterNewPassword: "أدخل كلمة المرور الجديدة",
        confirmNewPassword: "تأكيد كلمة المرور الجديدة",
        enterConfirmNewPassword: "أدخل كلمة المرور الجديدة مرة أخرى",
        currentPasswordRequired: "كلمة المرور الحالية مطلوبة",
        newPasswordRequired: "كلمة المرور الجديدة مطلوبة",
        confirmPasswordRequired: "تأكيد كلمة المرور مطلوب",
        passwordsDoNotMatch: "كلمات المرور غير متطابقة",
        newPasswordMustBeDifferent: "يجب أن تكون كلمة المرور الجديدة مختلفة عن الحالية",
        passwordChangedSuccessfully: "تم تغيير كلمة المرور بنجاح!",
        errorChangingPassword: "خطأ في تغيير كلمة المرور",
        changing: "جاري التغيير...",
        // Profile
        profile: "الملف الشخصي",
        profileSettings: "إعدادات الملف الشخصي",
        siteCustomization: "تخصيص الموقع",
        primaryColor: "اللون الأساسي",
        activeSubPageColor: "لون الصفحة الفرعية النشط",
        siteLogo: "شعار الموقع",
        profilePicture: "صورة الملف الشخصي",
        upload: "رفع",
        security: "الأمان",
        saveProfile: "حفظ الملف الشخصي",
        emailVerified: "البريد الإلكتروني مُتحقق منه",
        emailNotVerified: "البريد الإلكتروني غير مُتحقق منه. يرجى التحقق من صندوق الوارد لرسالة التحقق.",
        // Delete modals
        deleteChannel: "حذف القناة",
        confirmDeleteChannel: "هل أنت متأكد أنك تريد حذف",
        deleteStage: "حذف المرحلة",
        confirmDeleteStage: "هل أنت متأكد أنك تريد حذف",
        deleteStatus: "حذف الحالة",
        confirmDeleteStatus: "هل أنت متأكد أنك تريد حذف",
        cannotDeleteDefault: "لا يمكن حذف الحالة الافتراضية",
        // Registration
        register: "التسجيل",
        dontHaveAccount: "ليس لديك حساب؟",
        forgotPassword: "هل نسيت كلمة المرور؟",
        alreadyHaveAccount: "هل لديك حساب بالفعل؟",
        createAccount: "إنشاء حسابك",
        registerDescription: "ابدأ إدارة عملك مع نظام CRM القوي لدينا. ابدأ في دقائق.",
        createCompanyAccount: "إنشاء حساب شركتك",
        companyInformation: "معلومات الشركة",
        companyName: "اسم الشركة",
        enterCompanyName: "أدخل اسم الشركة",
        companyNameRequired: "اسم الشركة مطلوب",
        companyDomain: "نطاق الشركة",
        enterCompanyDomain: "مثال: example.com",
        companyDomainRequired: "نطاق الشركة مطلوب",
        invalidDomain: "صيغة النطاق غير صحيحة",
        domainAlreadyExists: "نطاق الشركة موجود بالفعل",
        domainHint: "سيتم استخدامه كمعرف للشركة",
        realEstate: "العقارات",
        ownerInformation: "معلومات المالك",
        firstName: "الاسم الأول",
        enterFirstName: "أدخل الاسم الأول",
        firstNameRequired: "الاسم الأول مطلوب",
        lastName: "اسم العائلة",
        enterLastName: "أدخل اسم العائلة",
        lastNameRequired: "اسم العائلة مطلوب",
        enterEmail: "أدخل عنوان البريد الإلكتروني",
        enterUsername: "أدخل اسم المستخدم",
        enterPassword: "أدخل كلمة المرور",
        confirmPassword: "تأكيد كلمة المرور",
        selectPlan: "اختر خطة",
        planSelectionHint: "اختر الخطة التي تناسب فريقك. يمكنك التبديل لاحقاً ولا حاجة لتفاصيل الدفع الآن.",
        billingCycle: "دورة الفوترة",
        monthly: "شهري",
        yearly: "سنوي",
        loadingPlans: "جارٍ تحميل الخطط...",
        noPlansAvailable: "لا توجد خطط مدفوعة منشورة بعد. يمكنك المتابعة مع الفترة التجريبية المجانية.",
        freeTrial: "فترة تجريبية مجانية",
        trialDescription: "14 يوم تجريبي مجاني، لا حاجة لبطاقة ائتمان",
        free: "مجاني",
        plansWillBeAdded: "ستكون الخطط متاحة بعد التسجيل",
        planNoteNoPayment: "سنقوم بتفعيل الخطة التي اخترتها فوراً، ويمكنك الترقية أو التخفيض في أي وقت من الإعدادات.",
        planDefaultDescription: "جميع أساسيات إدارة علاقات العملاء مشمولة.",
        usersIncluded: "المستخدمون",
        clientsIncluded: "العملاء",
        storageIncluded: "التخزين",
        trialDaysLabel: "يوم تجريبي",
        perMonth: "شهرياً",
        perYear: "سنوياً",
        planRequired: "يرجى اختيار خطة للمتابعة",
        passwordRequirements: "استخدم 8 أحرف على الأقل مع حروف وأرقام وتجنب الكلمات الشائعة.",
        verifyEmailTitle: "تحقق من بريدك الإلكتروني",
        verifyEmailDescription: "أرسلنا رمزاً مكوّناً من 6 أرقام إلى بريدك. أدخله بالأسفل لتفعيل حسابك.",
        verificationSentTo: "تم الإرسال إلى",
        verificationExpiresAt: "ينتهي الرمز في",
        verificationCodeLabel: "رمز التحقق",
        verificationCodePlaceholder: "أدخل رمزاً من 6 أرقام",
        verificationSentMessage: "أرسلنا رمزاً مكوّناً من 6 أرقام إلى بريدك. أدخله بالأسفل لتفعيل حسابك.",
        verificationSendFailed: "تعذر إرسال بريد التحقق تلقائياً. يرجى التواصل مع الدعم أو استخدام الرابط داخل البريد عند وصوله.",
        verificationEmailMissing: "البريد الإلكتروني مفقود للتحقق.",
        verificationCodeRequired: "يرجى إدخال رمز التحقق المرسل إلى بريدك.",
        verificationSuccess: "تم التحقق من البريد الإلكتروني بنجاح! سيتم تحويلك الآن...",
        verificationFailed: "فشل التحقق. يرجى المحاولة مرة أخرى.",
        verifyLater: "التحقق لاحقاً",
        verifyNow: "تحقق الآن",
        verifyLaterHint: "إذا اخترت \"التحقق لاحقاً\" يمكنك دائماً إكمال العملية عبر الرابط الموجود في بريد التحقق.",
        verifyingEmail: "جارٍ التحقق من عنوان بريدك الإلكتروني...",
        verifying: "جارٍ التحقق...",
        verificationLinkInvalid: "رابط التحقق غير صالح. يرجى التحقق من بريدك الإلكتروني والمحاولة مرة أخرى.",
        emailVerifiedSuccessfully: "تم التحقق من بريدك الإلكتروني بنجاح! يمكنك الآن تسجيل الدخول.",
        goToLogin: "الذهاب إلى تسجيل الدخول",
        goToDashboard: "الذهاب إلى لوحة التحكم",
        verificationHelpText: "إذا استمرت المشاكل، يرجى التواصل مع الدعم أو طلب بريد تحقق جديد.",
        back: "رجوع",
        next: "التالي",
        registrationFailed: "فشل التسجيل. يرجى المحاولة مرة أخرى.",
        networkError: "خطأ في الشبكة: تعذر الاتصال بالخادم. يرجى التحقق من اتصال الإنترنت والتأكد من أن خادم API متاح.",
        // Forgot Password
        forgotPasswordDescription: "لا تقلق! أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور.",
        forgotPasswordSubtitle: "أدخل عنوان بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين",
        passwordResetEmailSent: "إذا كان البريد الإلكتروني موجوداً، تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني. يرجى التحقق من صندوق الوارد.",
        sendResetLink: "إرسال رابط إعادة التعيين",
        rememberPassword: "تذكرت كلمة المرور؟",
        pleaseEnterEmail: "الرجاء إدخال عنوان بريدك الإلكتروني",
        invalidEmailFormat: "الرجاء إدخال عنوان بريد إلكتروني صحيح",
        // Reset Password
        resetPassword: "إعادة تعيين كلمة المرور",
        resetPasswordDescription: "أدخل كلمة المرور الجديدة أدناه لإكمال عملية إعادة التعيين.",
        enterNewPasswordBelow: "أدخل كلمة المرور الجديدة أدناه",
        passwordResetSuccess: "تم إعادة تعيين كلمة المرور بنجاح! جاري التحويل إلى صفحة تسجيل الدخول...",
        pleaseEnterCodeOrToken: "الرجاء إدخال رمز إعادة التعيين أو استخدام رابط إعادة التعيين",
        pleaseEnterNewPassword: "الرجاء إدخال كلمة مرور جديدة",
        passwordTooShort: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
        resetCode: "رمز إعادة التعيين",
        emailAddress: "البريد الإلكتروني",
        enterCodeFromEmail: "أدخل الرمز المكون من 6 أرقام المرسل إلى بريدك الإلكتروني",
        chooseResetMethod: "يمكنك إما الضغط على الرابط في بريدك الإلكتروني أو إدخال الرمز أدناه:",
        continueWithCode: "المتابعة بالرمز",
        orClickLinkInEmail: "أو اضغط على الرابط في بريدك الإلكتروني للمتابعة",
        pleaseEnterCode: "الرجاء إدخال رمز إعادة التعيين",
        codeMustBe6Digits: "يجب أن يكون الرمز 6 أرقام",
        usingCodeToReset: "استخدام الرمز لإعادة تعيين كلمة المرور",
        // Two Factor Authentication
        twoFactorAuth: "المصادقة الثنائية",
        twoFactorAuthTitle: "المصادقة الثنائية",
        twoFactorAuthDescription: "لضمان أمان حسابك، يرجى إدخال رمز المصادقة الثنائية الذي تم إرساله إلى بريدك الإلكتروني",
        enter2FACode: "أدخل رمز المصادقة الثنائية المكون من 6 أرقام",
        twoFactorCodeLabel: "رمز المصادقة الثنائية",
        twoFactorCodePlaceholder: "000000",
        verify: "التحقق",
        didntReceiveCode: "لم تستلم الرمز؟",
        resendCode: "إعادة إرسال الرمز",
        resendCodeCountdown: "إعادة الإرسال ({countdown} ثانية)",
        backToLogin: "العودة إلى تسجيل الدخول",
        twoFactorCodeSent: "تم إرسال رمز المصادقة الثنائية إلى بريدك الإلكتروني",
        pleaseEnter2FACode: "الرجاء إدخال رمز المصادقة الثنائية المكون من 6 أرقام",
        twoFactorCodeInvalid: "رمز المصادقة الثنائية غير صحيح",
        twoFactorCodeExpired: "انتهت صلاحية رمز المصادقة الثنائية. يرجى طلب رمز جديد",
        twoFactorCodeRequired: "الرجاء إدخال رمز المصادقة الثنائية",
        twoFactorCodeLengthError: "يجب أن يكون الرمز 6 أرقام",
        twoFactorAuthFailed: "فشل التحقق من رمز المصادقة الثنائية",
        twoFactorAuthRequestFailed: "فشل طلب رمز المصادقة الثنائية",
        // Filter Drawers
        filterActivities: "تصفية الأنشطة",
        activityInfo: "معلومات النشاط",
        leadType: "نوع العميل",
        timePeriod: "الفترة الزمنية",
        time: "الوقت",
        activityDateFrom: "تاريخ النشاط (من)",
        activityDateTo: "تاريخ النشاط (إلى)",
        filterCampaigns: "تصفية الحملات",
        campaignInfo: "معلومات الحملة",
        campaignCreatedAtFrom: "تاريخ إنشاء الحملة (من)",
        campaignCreatedAtTo: "تاريخ إنشاء الحملة (إلى)",
        searchByNameOrCode: "البحث بالاسم أو الرمز",
        filterProjects: "تصفية المشاريع",
        projectInfo: "معلومات المشروع",
        filterServicePackages: "تصفية باقات الخدمات",
        packageInfo: "معلومات الباقة",
        priceRangeStart: "بداية نطاق السعر",
        priceRangeEnd: "نهاية نطاق السعر",
        filterProducts: "تصفية المنتجات",
        productInfo: "معلومات المنتج",
        stockRangeStart: "بداية نطاق المخزون",
        stockRangeEnd: "نهاية نطاق المخزون",
        filterServices: "تصفية الخدمات",
        serviceInfo: "معلومات الخدمة",
        filterServiceProviders: "تصفية مقدمي الخدمات",
        providerInfo: "معلومات مقدم الخدمة",
        filterSuppliers: "تصفية الموردين",
        supplierInfo: "معلومات المورد",
        searchByClientNameOrId: "البحث باسم العميل أو معرف الصفقة",
        filterProductCategories: "تصفية فئات المنتجات",
        filterDevelopers: "تصفية المطورين",
        filterOwners: "تصفية الملاك",
        ownerInfo: "معلومات المالك",
        unitInfo: "معلومات الوحدة",
        valueRangeStart: "بداية نطاق القيمة",
        valueRangeEnd: "نهاية نطاق القيمة",
        // Payment
        paymentSubscriptionIdRequired: "معرف الاشتراك مطلوب",
        paymentRedirectError: "فشل الحصول على رابط الدفع",
        paymentInitError: "فشل تهيئة الدفع",
        paymentRedirecting: "جاري التوجيه إلى بوابة الدفع...",
        paymentError: "خطأ في الدفع",
        backToRegistration: "العودة إلى التسجيل",
        paymentProcessing: "جاري معالجة الدفع...",
        paymentSuccess: "تم الدفع بنجاح!",
        paymentSuccessMessage: "تم معالجة الدفع بنجاح. حسابك الآن نشط.",
        redirectingToDashboard: "جاري تحويلك إلى لوحة التحكم...",
        paymentSuccessNote: "سيتم تحويلك تلقائياً خلال ثوانٍ قليلة",
        paymentSuccessNoData: "تم الدفع بنجاح لكن لم يتم العثور على بيانات المستخدم. يرجى تسجيل الدخول.",
        paymentSuccessError: "خطأ في معالجة نجاح الدفع",
        paymentPending: "جاري معالجة الدفع. يرجى الانتظار قليلاً وإعادة التحديث.",
        noActiveSubscription: "اشتراكك غير نشط. يرجى التواصل مع الدعم أو إكمال عملية الدفع للوصول إلى النظام.",
        noActiveSubscriptionBeforeLink: "اشتراكك غير نشط. يرجى التواصل مع الدعم أو ",
        noActiveSubscriptionAfterLink: " للوصول إلى النظام.",
        completePayment: "إكمال عملية الدفع",
        completePaymentViaPaytabs: "إكمال الدفع عبر Paytabs",
    }
};