import { translations } from '../constants';

type Lang = 'en' | 'ar';
type TranslationKey = keyof typeof translations.en;

type DealTermKey = TranslationKey;

type Pack = Partial<Record<DealTermKey, string>>;

const SERVICES_EN: Pack = {
  deals: 'Contracts',
  deal: 'Contract',
  createDeal: 'Create contract',
  createNewDeal: 'New contract',
  addDeal: 'Add contract',
  deleteDeal: 'Delete contract',
  viewDeal: 'View contract',
  editDeal: 'Edit contract',
  searchDeals: 'Search contracts',
  noDealsFound: 'No contracts found.',
  filterDeals: 'Filter contracts',
  dealInfo: 'Contract information',
  dealInformation: 'Contract information',
  confirmDeleteDeal: 'Are you sure you want to delete the contract for',
  dealUpdatedSuccessfully: 'Contract updated successfully!',
  dealCreatedSuccessfully: 'Contract created successfully!',
  errorLoadingDeals: 'Error loading contracts. Please try again.',
  errorUpdatingDeal: 'Failed to update contract. Please try again.',
  errorCreatingDeal: 'Failed to create contract. Please try again.',
  exportDeals: 'Export contracts to Excel',
  totalDeals: 'Total contracts',
  completedDeals: 'Completed contracts',
  averageDealSize: 'Avg. contract value',
  wonDeals: 'Won contracts',
  supervisorsPermCanManageDeals: 'Contracts',
  dealRequiredForTask: 'Contract information is required to complete this task',
  dealStage: 'Contract stage',
  selectDeal: 'Select contract',
  enterNotesAboutDeal: 'Enter notes about the contract',
  valueRequired: 'Contract value is required and must be greater than 0',
  dealId: 'ID',
  dealCreatedAtRange: 'Contract created date range',
};

const SERVICES_AR: Pack = {
  deals: 'العقود',
  deal: 'عقد',
  createDeal: 'إنشاء عقد',
  createNewDeal: 'عقد جديد',
  addDeal: 'إضافة عقد',
  deleteDeal: 'حذف العقد',
  viewDeal: 'عرض العقد',
  editDeal: 'تعديل العقد',
  searchDeals: 'بحث في العقود',
  noDealsFound: 'لا توجد عقود.',
  filterDeals: 'تصفية العقود',
  dealInfo: 'معلومات العقد',
  dealInformation: 'معلومات العقد',
  confirmDeleteDeal: 'هل أنت متأكد أنك تريد حذف العقد لـ',
  dealUpdatedSuccessfully: 'تم تحديث العقد بنجاح!',
  dealCreatedSuccessfully: 'تم إنشاء العقد بنجاح!',
  errorLoadingDeals: 'خطأ في تحميل العقود. يرجى المحاولة مرة أخرى.',
  errorUpdatingDeal: 'فشل تحديث العقد. يرجى المحاولة مرة أخرى.',
  errorCreatingDeal: 'فشل إنشاء العقد. يرجى المحاولة مرة أخرى.',
  exportDeals: 'تصدير العقود إلى Excel',
  totalDeals: 'إجمالي العقود',
  completedDeals: 'العقود المكتملة',
  averageDealSize: 'متوسط قيمة العقد',
  wonDeals: 'عقود مكتملة',
  supervisorsPermCanManageDeals: 'العقود',
  dealRequiredForTask: 'معلومات العقد مطلوبة لإكمال هذه المهمة',
  dealStage: 'مرحلة العقد',
  selectDeal: 'اختر العقد',
  enterNotesAboutDeal: 'أدخل ملاحظات حول العقد',
  valueRequired: 'قيمة العقد مطلوبة ويجب أن تكون أكبر من 0',
  dealId: 'المعرف',
  dealCreatedAtRange: 'نطاق تاريخ إنشاء العقد',
};

const PRODUCTS_EN: Pack = {
  deals: 'Orders',
  deal: 'Order',
  createDeal: 'Create order',
  createNewDeal: 'New order',
  addDeal: 'Add order',
  deleteDeal: 'Delete order',
  viewDeal: 'View order',
  editDeal: 'Edit order',
  searchDeals: 'Search orders',
  noDealsFound: 'No orders found.',
  filterDeals: 'Filter orders',
  dealInfo: 'Order information',
  dealInformation: 'Order information',
  confirmDeleteDeal: 'Are you sure you want to delete the order for',
  dealUpdatedSuccessfully: 'Order updated successfully!',
  dealCreatedSuccessfully: 'Order created successfully!',
  errorLoadingDeals: 'Error loading orders. Please try again.',
  errorUpdatingDeal: 'Failed to update order. Please try again.',
  errorCreatingDeal: 'Failed to create order. Please try again.',
  exportDeals: 'Export orders to Excel',
  totalDeals: 'Total orders',
  completedDeals: 'Completed orders',
  averageDealSize: 'Avg. order value',
  wonDeals: 'Fulfilled orders',
  supervisorsPermCanManageDeals: 'Orders',
  dealRequiredForTask: 'Order information is required to complete this task',
  dealStage: 'Order stage',
  selectDeal: 'Select order',
  enterNotesAboutDeal: 'Enter notes about the order',
  valueRequired: 'Order value is required and must be greater than 0',
  dealId: 'ID',
  dealCreatedAtRange: 'Order created date range',
};

const PRODUCTS_AR: Pack = {
  deals: 'الطلبات',
  deal: 'طلبية',
  createDeal: 'إنشاء طلبية',
  createNewDeal: 'طلبية جديدة',
  addDeal: 'إضافة طلبية',
  deleteDeal: 'حذف الطلبية',
  viewDeal: 'عرض الطلبية',
  editDeal: 'تعديل الطلبية',
  searchDeals: 'بحث في الطلبات',
  noDealsFound: 'لا توجد طلبات.',
  filterDeals: 'تصفية الطلبات',
  dealInfo: 'معلومات الطلبية',
  dealInformation: 'معلومات الطلبية',
  confirmDeleteDeal: 'هل أنت متأكد أنك تريد حذف الطلبية لـ',
  dealUpdatedSuccessfully: 'تم تحديث الطلبية بنجاح!',
  dealCreatedSuccessfully: 'تم إنشاء الطلبية بنجاح!',
  errorLoadingDeals: 'خطأ في تحميل الطلبات. يرجى المحاولة مرة أخرى.',
  errorUpdatingDeal: 'فشل تحديث الطلبية. يرجى المحاولة مرة أخرى.',
  errorCreatingDeal: 'فشل إنشاء الطلبية. يرجى المحاولة مرة أخرى.',
  exportDeals: 'تصدير الطلبات إلى Excel',
  totalDeals: 'إجمالي الطلبات',
  completedDeals: 'الطلبات المكتملة',
  averageDealSize: 'متوسط قيمة الطلبية',
  wonDeals: 'طلبيات مكتملة',
  supervisorsPermCanManageDeals: 'الطلبات',
  dealRequiredForTask: 'معلومات الطلبية مطلوبة لإكمال هذه المهمة',
  dealStage: 'مرحلة الطلبية',
  selectDeal: 'اختر الطلبية',
  enterNotesAboutDeal: 'أدخل ملاحظات حول الطلبية',
  valueRequired: 'قيمة الطلبية مطلوبة ويجب أن تكون أكبر من 0',
  dealId: 'المعرف',
  dealCreatedAtRange: 'نطاق تاريخ إنشاء الطلبية',
};

const MEDICAL_EN: Pack = {
  deals: 'Treatment plans',
  deal: 'Treatment plan',
  createDeal: 'Create treatment plan',
  createNewDeal: 'New treatment plan',
  addDeal: 'Add treatment plan',
  deleteDeal: 'Delete treatment plan',
  viewDeal: 'View treatment plan',
  editDeal: 'Edit treatment plan',
  searchDeals: 'Search treatment plans',
  noDealsFound: 'No treatment plans found.',
  filterDeals: 'Filter treatment plans',
  dealInfo: 'Treatment plan information',
  dealInformation: 'Treatment plan information',
  confirmDeleteDeal: 'Are you sure you want to delete the treatment plan for',
  dealUpdatedSuccessfully: 'Treatment plan updated successfully!',
  dealCreatedSuccessfully: 'Treatment plan created successfully!',
  errorLoadingDeals: 'Error loading treatment plans. Please try again.',
  errorUpdatingDeal: 'Failed to update treatment plan. Please try again.',
  errorCreatingDeal: 'Failed to create treatment plan. Please try again.',
  exportDeals: 'Export treatment plans to Excel',
  totalDeals: 'Total treatment plans',
  completedDeals: 'Completed treatment plans',
  averageDealSize: 'Avg. plan value',
  wonDeals: 'Completed plans',
  supervisorsPermCanManageDeals: 'Treatment plans',
  dealRequiredForTask: 'Treatment plan information is required to complete this task',
  dealStage: 'Plan stage',
  selectDeal: 'Select treatment plan',
  enterNotesAboutDeal: 'Enter notes about the treatment plan',
  valueRequired: 'Plan amount is required and must be greater than 0',
  dealId: 'ID',
  dealCreatedAtRange: 'Plan created date range',
};

const MEDICAL_AR: Pack = {
  deals: 'خطط العلاج',
  deal: 'خطة علاج',
  createDeal: 'إنشاء خطة علاج',
  createNewDeal: 'خطة علاج جديدة',
  addDeal: 'إضافة خطة علاج',
  deleteDeal: 'حذف خطة العلاج',
  viewDeal: 'عرض خطة العلاج',
  editDeal: 'تعديل خطة العلاج',
  searchDeals: 'بحث في خطط العلاج',
  noDealsFound: 'لا توجد خطط علاج.',
  filterDeals: 'تصفية خطط العلاج',
  dealInfo: 'معلومات خطة العلاج',
  dealInformation: 'معلومات خطة العلاج',
  confirmDeleteDeal: 'هل أنت متأكد أنك تريد حذف خطة العلاج لـ',
  dealUpdatedSuccessfully: 'تم تحديث خطة العلاج بنجاح!',
  dealCreatedSuccessfully: 'تم إنشاء خطة العلاج بنجاح!',
  errorLoadingDeals: 'خطأ في تحميل خطط العلاج. يرجى المحاولة مرة أخرى.',
  errorUpdatingDeal: 'فشل تحديث خطة العلاج. يرجى المحاولة مرة أخرى.',
  errorCreatingDeal: 'فشل إنشاء خطة العلاج. يرجى المحاولة مرة أخرى.',
  exportDeals: 'تصدير خطط العلاج إلى Excel',
  totalDeals: 'إجمالي خطط العلاج',
  completedDeals: 'خطط علاج مكتملة',
  averageDealSize: 'متوسط قيمة الخطة',
  wonDeals: 'خطط مكتملة',
  supervisorsPermCanManageDeals: 'خطط العلاج',
  dealRequiredForTask: 'معلومات خطة العلاج مطلوبة لإكمال هذه المهمة',
  dealStage: 'مرحلة الخطة',
  selectDeal: 'اختر خطة العلاج',
  enterNotesAboutDeal: 'أدخل ملاحظات حول خطة العلاج',
  valueRequired: 'مبلغ الخطة مطلوب ويجب أن يكون أكبر من 0',
  dealId: 'المعرف',
  dealCreatedAtRange: 'نطاق تاريخ إنشاء خطة العلاج',
};

const BY_SPEC: Record<string, Record<Lang, Pack>> = {
  services: { en: SERVICES_EN, ar: SERVICES_AR },
  products: { en: PRODUCTS_EN, ar: PRODUCTS_AR },
  medical: { en: MEDICAL_EN, ar: MEDICAL_AR },
};

export function getDealTerminologyOverride(
  specialization: string | undefined | null,
  language: Lang,
  key: TranslationKey
): string | undefined {
  const spec = String(specialization || '').toLowerCase();
  const pack = BY_SPEC[spec]?.[language];
  if (!pack) return undefined;
  const v = pack[key as DealTermKey];
  return v !== undefined && v !== '' ? v : undefined;
}
